import assert from 'node:assert/strict';
import artifactProvenance from '../../../../wasm/artifact-provenance.json' with { type: 'json' };
import type { PlateId } from '../../project/domain/ids';
import { SliceRouteCancellationError, SliceRouteError } from '../../project/slicing/SliceJobCoordinator';
import { SLICE_PROTOCOL_VERSION, type SliceRouteRequest } from '../../project/slicing/types';
import {
  BROWSER_WASM_ENGINE_METADATA,
  CanonicalSlicerClientRoute,
  type CanonicalProjectSlicerClientPort,
  type CanonicalSlicerRouteProgress,
} from '../CanonicalSlicerClientRoute';
import {
  SlicerClient,
  SlicerClientCancellationError,
  type SlicerClientProjectRoute,
  type SlicerClientProjectSliceOptions,
} from '../SlicerClient';

const encoder = new TextEncoder();
let passed = 0;

class MemoryStorage implements Storage {
  private readonly values = new Map<string, string>();
  get length(): number {
    return this.values.size;
  }
  clear(): void {
    this.values.clear();
  }
  getItem(key: string): string | null {
    return this.values.get(key) ?? null;
  }
  key(index: number): string | null {
    return [...this.values.keys()][index] ?? null;
  }
  removeItem(key: string): void {
    this.values.delete(key);
  }
  setItem(key: string, value: string): void {
    this.values.set(key, value);
  }
}

async function test(name: string, run: () => Promise<void> | void): Promise<void> {
  await run();
  passed += 1;
  console.log(`  ✓ ${name}`);
}

class RecordingClient implements CanonicalProjectSlicerClientPort {
  calls: Array<{
    project: Uint8Array;
    route: SlicerClientProjectRoute;
    options: SlicerClientProjectSliceOptions;
  }> = [];

  async sliceProjectWithRoute(
    project: ArrayBuffer,
    route: SlicerClientProjectRoute,
    options: SlicerClientProjectSliceOptions = {},
  ): Promise<string> {
    this.calls.push({ project: new Uint8Array(project).slice(), route, options });
    options.onProgress?.({ percent: 37, message: 'Generating infill' });
    return '; generated by fixture\nG1 X1 Y2 E3\n';
  }
}

await test('browser adapter submits copied canonical bytes with tracked engine provenance and contextual progress', async () => {
  const client = new RecordingClient();
  const progress: CanonicalSlicerRouteProgress[] = [];
  const adapter = new CanonicalSlicerClientRoute({
    client,
    route: { kind: 'browser-wasm' },
    onProgress: (p) => progress.push(p),
  });
  const request = requestFor(adapter.metadata.engine);
  const sourceFirstByte = request.project.bytes[0];
  const protocolProgress: Array<{ percent?: number; message?: string }> = [];
  const response = await adapter.execute(request, new AbortController().signal, (value) =>
    protocolProgress.push(value),
  );

  assert.equal(adapter.metadata.kind, 'browser-wasm');
  assert.equal(adapter.metadata.engine.commit, artifactProvenance.engine.commit);
  assert.equal(adapter.metadata.engine.artifactHash, `sha256:${artifactProvenance.outputs['slic3r.wasm']}`);
  assert.deepEqual(adapter.metadata.engine, BROWSER_WASM_ENGINE_METADATA);
  assert.deepEqual(client.calls[0].route, { kind: 'browser-wasm' });
  assert.equal(client.calls[0].options.allowUncancellableMainThreadFallback, false);
  client.calls[0].project[0] = 0;
  assert.equal(request.project.bytes[0], sourceFirstByte, 'the SlicerClient cannot mutate coordinator-owned bytes');
  assert.deepEqual(progress, [
    {
      jobId: request.jobId,
      plateId: request.plateId,
      attempt: 1,
      routeId: adapter.metadata.id,
      percent: 37,
      message: 'Generating infill',
    },
  ]);
  assert.deepEqual(protocolProgress, [{ percent: 37, message: 'Generating infill' }]);
  assert.equal(new TextDecoder().decode(response.gcode), '; generated by fixture\nG1 X1 Y2 E3\n');
  assert.deepEqual(response.engine, adapter.metadata.engine);
  assert.deepEqual(response.statistics, { route: 'browser-wasm', gcodeBytes: response.gcode.byteLength });
});

await test('external routes require explicit engine attestation and reject secret-bearing URLs', () => {
  const client = new RecordingClient();
  assert.throws(
    () =>
      new CanonicalSlicerClientRoute({
        client,
        route: { kind: 'external-server', endpoint: 'https://slicer.example.test/api' },
      }),
    /attested engine commit and artifact hash/,
  );

  for (const endpoint of [
    'https://user:secret@slicer.example.test/api',
    'https://slicer.example.test/api?token=nope',
    'https://slicer.example.test/api?',
    'https://slicer.example.test/api#fragment',
    'https://slicer.example.test/api#',
  ]) {
    assert.throws(
      () =>
        new CanonicalSlicerClientRoute({
          client,
          route: { kind: 'external-server', endpoint },
          externalEngine: { commit: 'server-commit', artifactHash: 'sha256:server-artifact' },
        }),
      /cannot contain credentials, query parameters, or fragments/,
    );
  }

  const adapter = new CanonicalSlicerClientRoute({
    client,
    route: { kind: 'external-server', endpoint: 'https://slicer.example.test/api/' },
    externalEngine: { commit: 'server-commit', artifactHash: 'sha256:server-artifact' },
  });
  assert.equal(adapter.metadata.kind, 'external-server');
  assert.equal(adapter.metadata.id, 'slicer-client:external-server:https://slicer.example.test/api');
});

await test('engine-provenance mismatch fails before model bytes reach SlicerClient', async () => {
  const client = new RecordingClient();
  const adapter = new CanonicalSlicerClientRoute({ client, route: { kind: 'browser-wasm' } });
  const request = requestFor({ ...adapter.metadata.engine, artifactHash: 'sha256:wrong' });
  await assert.rejects(adapter.execute(request, new AbortController().signal), SliceRouteError);
  assert.equal(client.calls.length, 0);
});

await test('adapter preserves abort reasons and never converts cancellation into a retryable route failure', async () => {
  const reason = new Error('cancelled by fixture');
  const client: CanonicalProjectSlicerClientPort = {
    sliceProjectWithRoute(_project, _route, options) {
      return new Promise((_resolve, reject) => {
        options?.signal?.addEventListener('abort', () => reject(options.signal!.reason), { once: true });
      });
    },
  };
  const adapter = new CanonicalSlicerClientRoute({ client, route: { kind: 'browser-wasm' } });
  const controller = new AbortController();
  const pending = adapter.execute(requestFor(adapter.metadata.engine), controller.signal);
  controller.abort(reason);
  await assert.rejects(
    pending,
    (error: unknown) =>
      error instanceof SliceRouteCancellationError &&
      error.cancellationConfirmed &&
      error.cancellationReason === reason,
  );
});

await test('adapter does not mask an unconfirmed underlying cancellation', async () => {
  const unconfirmed = new SlicerClientCancellationError('server cancellation could not be confirmed', false);
  const client: CanonicalProjectSlicerClientPort = {
    async sliceProjectWithRoute() {
      throw unconfirmed;
    },
  };
  const adapter = new CanonicalSlicerClientRoute({ client, route: { kind: 'browser-wasm' } });
  // Exercise the race after execution starts; a pre-aborted signal never calls the route.
  const active = new AbortController();
  const pending = adapter.execute(requestFor(adapter.metadata.engine), active.signal);
  active.abort(new Error('cancel requested'));
  await assert.rejects(
    pending,
    (error: unknown) =>
      error instanceof SliceRouteCancellationError && !error.cancellationConfirmed && error.cause === unconfirmed,
  );
});

await test('local canonical abort terminates the dedicated worker instead of using the main-thread fallback', async () => {
  const restore = installBrowserWorkerHarness();
  try {
    const client = new SlicerClient();
    const controller = new AbortController();
    const reason = new Error('stop local worker');
    const pending = client.sliceProjectWithRoute(
      new ArrayBuffer(8),
      { kind: 'browser-wasm' },
      {
        signal: controller.signal,
        allowUncancellableMainThreadFallback: false,
      },
    );
    await waitUntil(() => restore.worker?.posted === true);
    controller.abort(reason);
    await assert.rejects(pending, (error: unknown) => error === reason);
    assert.equal(restore.worker?.terminated, true);
  } finally {
    restore.restore();
  }
});

await test('captured external preferences reject credentials, query parameters, and fragments before fetch', async () => {
  for (const endpoint of [
    'http://user:secret@slicer.local:3000',
    'http://slicer.local:3000?token=nope',
    'http://slicer.local:3000?',
    'http://slicer.local:3000#fragment',
    'http://slicer.local:3000#',
  ]) {
    const restore = installExternalHarness();
    try {
      restore.storage.setItem('external_slicer_url', endpoint);
      restore.storage.setItem('external_slicer_enabled', 'true');
      assert.throws(
        () => SlicerClient.captureProjectRoute(),
        /cannot contain credentials, query parameters, or fragments/,
      );
      await assert.rejects(
        new SlicerClient().sliceProjectWithRoute(new ArrayBuffer(8), { kind: 'external-server', endpoint }, {}),
        /cannot contain credentials, query parameters, or fragments/,
      );
      assert.equal(restore.requests.length, 0);
    } finally {
      restore.restore();
    }
  }
});

await test('external canonical abort waits for DELETE cancellation confirmation once a job ID exists', async () => {
  const restore = installExternalHarness();
  try {
    restore.storage.setItem('external_slicer_url', 'http://slicer.local:3000');
    restore.storage.setItem('external_slicer_enabled', 'true');
    let releasePost: ((response: Response) => void) | undefined;
    const postResponse = new Promise<Response>((resolve) => {
      releasePost = resolve;
    });
    restore.fetchImpl = async (request) => {
      restore.requests.push(request);
      const url = new URL(request.url);
      if (request.method === 'POST') return postResponse;
      if (request.method === 'DELETE') {
        return jsonResponse({ status: 'cancelling' }, 202);
      }
      if (url.pathname === '/jobs/job-1') return jsonResponse({ status: 'cancelled', percent: 0 });
      throw new Error(`Unexpected request: ${request.method} ${url.pathname}`);
    };

    const client = new SlicerClient();
    const controller = new AbortController();
    const reason = new Error('stop remote job');
    const pending = client.sliceProjectWithRoute(
      new ArrayBuffer(8),
      { kind: 'external-server', endpoint: 'http://slicer.local:3000' },
      { signal: controller.signal, externalPollIntervalMs: 1, externalCancellationTimeoutMs: 100 },
    );
    await waitUntil(() => restore.requests.some((request) => request.method === 'POST'));
    controller.abort(reason);
    releasePost?.(jsonResponse({ job: 'job-1' }, 202));
    await assert.rejects(pending, (error: unknown) => error === reason);
    assert.ok(restore.requests.some((request) => request.method === 'DELETE' && request.url.endsWith('/jobs/job-1')));
    assert.ok(restore.requests.some((request) => request.method === 'GET' && request.url.endsWith('/jobs/job-1')));
  } finally {
    restore.restore();
  }
});

await test('external async route forwards server progress and returns the completed G-code', async () => {
  const restore = installExternalHarness();
  try {
    restore.storage.setItem('external_slicer_url', 'http://progress.local:3000');
    restore.storage.setItem('external_slicer_enabled', 'true');
    let statusReads = 0;
    restore.fetchImpl = async (request) => {
      restore.requests.push(request);
      const url = new URL(request.url);
      if (request.method === 'POST') return jsonResponse({ job: 'job-progress' }, 202);
      if (url.pathname === '/jobs/job-progress/gcode') return new Response('; complete\nG1 X1\n');
      if (url.pathname === '/jobs/job-progress') {
        statusReads += 1;
        return statusReads === 1
          ? jsonResponse({ status: 'running', percent: 42, message: 'Generating supports' })
          : jsonResponse({ status: 'done', percent: 100 });
      }
      throw new Error(`Unexpected request: ${request.method} ${url.pathname}`);
    };
    const progress: Array<{ percent: number; message: string }> = [];
    const result = await new SlicerClient().sliceProjectWithRoute(
      new ArrayBuffer(8),
      { kind: 'external-server', endpoint: 'http://progress.local:3000' },
      { externalPollIntervalMs: 1, onProgress: (value) => progress.push(value) },
    );
    assert.equal(result, '; complete\nG1 X1\n');
    assert.deepEqual(progress, [
      { percent: 0, message: 'Slicing project externally...' },
      { percent: 42, message: 'Generating supports' },
    ]);
  } finally {
    restore.restore();
  }
});

await test('legacy synchronous external responses report that cancellation was not confirmed', async () => {
  const restore = installExternalHarness();
  try {
    restore.storage.setItem('external_slicer_url', 'http://legacy.local:3000');
    restore.storage.setItem('external_slicer_enabled', 'true');
    let releasePost: ((response: Response) => void) | undefined;
    const postResponse = new Promise<Response>((resolve) => {
      releasePost = resolve;
    });
    restore.fetchImpl = async (request) => {
      restore.requests.push(request);
      return postResponse;
    };
    const controller = new AbortController();
    const pending = new SlicerClient().sliceProjectWithRoute(
      new ArrayBuffer(8),
      { kind: 'external-server', endpoint: 'http://legacy.local:3000' },
      { signal: controller.signal },
    );
    await waitUntil(() => restore.requests.length === 1);
    controller.abort('cancelled');
    releasePost?.(new Response('already completed', { status: 200 }));
    await assert.rejects(
      pending,
      (error: unknown) => error instanceof SlicerClientCancellationError && !error.cancellationConfirmed,
    );
  } finally {
    restore.restore();
  }
});

function requestFor(engine: SliceRouteRequest['engine']): SliceRouteRequest {
  return {
    protocolVersion: SLICE_PROTOCOL_VERSION,
    jobId: 'job-fixture',
    attempt: 1,
    plateId: 'plate-fixture' as PlateId,
    project: {
      bytes: encoder.encode('PK fixture canonical archive'),
      mediaType: 'model/3mf',
      inputHash: 'sha256:input',
      sourceRevision: 7,
      sourceHash: 'fnv1a64:source',
      sourceAssetHash: 'fnv1a64:assets',
    },
    profiles: { references: [], effectiveConfigHash: 'sha256:profiles' },
    engine,
    plateOverrides: {},
  };
}

function installExternalHarness(): {
  storage: MemoryStorage;
  requests: Request[];
  fetchImpl: (request: Request) => Promise<Response>;
  restore(): void;
} {
  const originalStorage = Object.getOwnPropertyDescriptor(globalThis, 'localStorage');
  const originalFetch = Object.getOwnPropertyDescriptor(globalThis, 'fetch');
  const storage = new MemoryStorage();
  const harness = {
    storage,
    requests: [] as Request[],
    fetchImpl: async (_request: Request): Promise<Response> => {
      throw new Error('fetchImpl not installed');
    },
    restore() {
      restoreProperty('localStorage', originalStorage);
      restoreProperty('fetch', originalFetch);
    },
  };
  Object.defineProperty(globalThis, 'localStorage', { configurable: true, value: storage });
  Object.defineProperty(globalThis, 'fetch', {
    configurable: true,
    value: (request: Request) => harness.fetchImpl(request),
  });
  return harness;
}

function installBrowserWorkerHarness(): {
  worker?: FakeWorker;
  restore(): void;
} {
  const descriptors = new Map(
    ['Worker', 'self', 'crossOriginIsolated'].map((name) => [name, Object.getOwnPropertyDescriptor(globalThis, name)]),
  );
  const harness: { worker?: FakeWorker; restore(): void } = {
    restore() {
      for (const [name, descriptor] of descriptors) restoreProperty(name, descriptor);
    },
  };
  Object.defineProperty(globalThis, 'crossOriginIsolated', { configurable: true, value: true });
  Object.defineProperty(globalThis, 'self', {
    configurable: true,
    value: { location: { origin: 'https://app.example.test' } },
  });
  Object.defineProperty(globalThis, 'Worker', {
    configurable: true,
    value: class {
      onmessage: ((event: MessageEvent) => void) | null = null;
      onerror: ((event: ErrorEvent) => void) | null = null;
      posted = false;
      terminated = false;
      constructor() {
        harness.worker = this;
      }
      postMessage(): void {
        this.posted = true;
      }
      terminate(): void {
        this.terminated = true;
      }
    } satisfies typeof FakeWorker,
  });
  return harness;
}

class FakeWorker {
  onmessage: ((event: MessageEvent) => void) | null = null;
  onerror: ((event: ErrorEvent) => void) | null = null;
  posted = false;
  terminated = false;
  postMessage(): void {}
  terminate(): void {}
}

function restoreProperty(name: string, descriptor: PropertyDescriptor | undefined): void {
  if (descriptor) Object.defineProperty(globalThis, name, descriptor);
  else Reflect.deleteProperty(globalThis, name);
}

function jsonResponse(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), { status, headers: { 'Content-Type': 'application/json' } });
}

async function waitUntil(condition: () => boolean): Promise<void> {
  for (let attempt = 0; attempt < 100; attempt += 1) {
    if (condition()) return;
    await new Promise((resolve) => setTimeout(resolve, 0));
  }
  throw new Error('Timed out waiting for test condition');
}

console.log(`\nCanonical SlicerClient route: ${passed} tests passed.`);
