/**
 * The thumbnail block a printer's display reads.
 *
 * A printer parses this by pattern: a block that is nearly right shows nothing
 * at all, and "nothing at all" is indistinguishable from the bug this replaced.
 * So the format is asserted against the pinned engine's own writer
 * (`GCodeThumbnails::export_thumbnails_to_file`) rather than against what looks
 * reasonable.
 */
import assert from 'node:assert/strict';
import {
  encodeThumbnailBlock,
  injectGcodeThumbnails,
  parseThumbnailList,
  type GcodeThumbnailRequest,
} from '../GcodeThumbnails';

let passed = 0;
function test(name: string, run: () => void): void {
  run();
  passed += 1;
  console.log(`  ✓ ${name}`);
}

test('the two shapes the profile corpus actually holds both parse', () => {
  // Snapmaker U1: a string with explicit formats.
  assert.deepEqual(parseThumbnailList('48x48/PNG, 300x300/PNG').requests, [
    { width: 48, height: 48, format: 'PNG' },
    { width: 300, height: 300, format: 'PNG' },
  ]);
  // Elegoo Centauri Carbon: a one-element vector with no format at all.
  assert.deepEqual(parseThumbnailList(['144x144']).requests, [{ width: 144, height: 144, format: 'PNG' }]);
  // PNG is the engine's default extension, and JPEG spells itself two ways.
  assert.deepEqual(parseThumbnailList('64x64/JPG').requests, [{ width: 64, height: 64, format: 'JPG' }]);
  assert.deepEqual(parseThumbnailList('64x64/jpeg').requests, [{ width: 64, height: 64, format: 'JPG' }]);
});

test('a request that cannot be honoured is stated, not dropped', () => {
  // The engine's own bound is 0 < size < 1000 on both axes.
  assert.deepEqual(parseThumbnailList('0x48').problems, [{ entry: '0x48', reason: 'out-of-range' }]);
  assert.deepEqual(parseThumbnailList('1000x48').problems, [{ entry: '1000x48', reason: 'out-of-range' }]);
  assert.deepEqual(parseThumbnailList('48').problems, [{ entry: '48', reason: 'invalid' }]);
  // A format a canvas cannot produce must not be emitted under someone else's
  // tag: the printer would read the block, decode garbage, and draw nothing.
  assert.deepEqual(parseThumbnailList('48x48/QOI').problems, [{ entry: '48x48/QOI', reason: 'unsupported-format' }]);
  assert.deepEqual(parseThumbnailList('48x48/QOI').requests, []);
  // A good entry beside a bad one still gets written.
  const mixed = parseThumbnailList('48x48/PNG, 5000x5000, 300x300');
  assert.equal(mixed.requests.length, 2);
  assert.equal(mixed.problems.length, 1);
});

test('nothing at all is a clean empty list rather than a throw', () => {
  assert.deepEqual(parseThumbnailList(undefined), { requests: [], problems: [] });
  assert.deepEqual(parseThumbnailList(''), { requests: [], problems: [] });
  assert.deepEqual(parseThumbnailList([]), { requests: [], problems: [] });
});

test('the block is byte-for-byte what the engine writes', () => {
  const request: GcodeThumbnailRequest = { width: 4, height: 4, format: 'PNG' };
  const block = encodeThumbnailBlock(request, new Uint8Array([1, 2, 3, 4, 5, 6]));
  // `output("; THUMBNAIL_BLOCK_START\n")`, then the odd but exact
  // `"\n;\n; %s begin %dx%d %d\n"`, the rows, the end tag, and a blank line.
  assert.equal(
    block,
    '; THUMBNAIL_BLOCK_START\n\n;\n; thumbnail begin 4x4 8\n; AQIDBAUG\n; thumbnail end\n; THUMBNAIL_BLOCK_END\n\n',
  );
  // The length in the header is the *base64* length, which is what a parser
  // reads to know how much to accumulate.
  assert.match(block, /; thumbnail begin 4x4 8\n/);
  assert.equal('AQIDBAUG'.length, 8);
});

test('rows wrap at 78 characters, as the engine wraps them', () => {
  const image = new Uint8Array(300).map((_, index) => index % 251);
  const block = encodeThumbnailBlock({ width: 8, height: 8, format: 'PNG' }, image);
  const rows = block.split('\n').filter((line) => line.startsWith('; ') && !/begin|end|BLOCK/.test(line));
  assert.ok(rows.length > 1, 'a 300-byte image must not fit on one row');
  for (const row of rows.slice(0, -1)) {
    assert.equal(row.length, 2 + 78, `row "${row.slice(0, 12)}…" is not a full 78-character row`);
  }
  // Reassembling the rows gives back exactly the image.
  const base64 = rows.map((row) => row.slice(2)).join('');
  assert.deepEqual(new Uint8Array(Buffer.from(base64, 'base64')), image);
});

test('a JPEG block carries the engine’s own tag for it', () => {
  const block = encodeThumbnailBlock({ width: 4, height: 4, format: 'JPG' }, new Uint8Array([9]));
  assert.match(block, /; thumbnail_JPG begin 4x4 /);
  assert.match(block, /; thumbnail_JPG end\n/);
});

const HEADER = [
  '; HEADER_BLOCK_START',
  '; generated by Snapmaker Orca 2.3.4',
  '; total layer number: 100',
  '; HEADER_BLOCK_END',
  '',
  '; external perimeters extrusion width = 0.45mm',
  '',
  '; EXECUTABLE_BLOCK_START',
  'G1 X10 Y10',
  '',
].join('\n');

test('the block lands where GCode.cpp writes it', () => {
  const block = encodeThumbnailBlock({ width: 4, height: 4, format: 'PNG' }, new Uint8Array([1]));
  const out = injectGcodeThumbnails(HEADER, [block]);
  const lines = out.split('\n');
  // After `HEADER_BLOCK_END` and its blank line, before the extrusion widths.
  assert.equal(lines[3], '; HEADER_BLOCK_END');
  assert.equal(lines[4], '');
  assert.equal(lines[5], '; THUMBNAIL_BLOCK_START');
  assert.ok(out.indexOf('; THUMBNAIL_BLOCK_END') < out.indexOf('; external perimeters'));
  // Nothing is lost or reordered.
  assert.ok(out.includes('G1 X10 Y10'));
  assert.ok(out.indexOf('; EXECUTABLE_BLOCK_START') > out.indexOf('; external perimeters'));
});

test('several thumbnails are written in the order the printer asked for them', () => {
  const small = encodeThumbnailBlock({ width: 48, height: 48, format: 'PNG' }, new Uint8Array([1]));
  const large = encodeThumbnailBlock({ width: 300, height: 300, format: 'PNG' }, new Uint8Array([2]));
  const out = injectGcodeThumbnails(HEADER, [small, large]);
  assert.ok(out.indexOf('begin 48x48') < out.indexOf('begin 300x300'));
  assert.equal(out.match(/; THUMBNAIL_BLOCK_START/g)?.length, 2);
});

test('a file that already carries a thumbnail is left alone', () => {
  const block = encodeThumbnailBlock({ width: 4, height: 4, format: 'PNG' }, new Uint8Array([1]));
  const once = injectGcodeThumbnails(HEADER, [block]);
  assert.equal(injectGcodeThumbnails(once, [block]), once, 'a second pass must not add a second set');
});

test('nothing to write leaves the G-code untouched', () => {
  assert.equal(injectGcodeThumbnails(HEADER, []), HEADER);
});

test('a program with no header block still gets its thumbnail somewhere readable', () => {
  const block = encodeThumbnailBlock({ width: 4, height: 4, format: 'PNG' }, new Uint8Array([1]));
  const bare = 'G28\nG1 X0 Y0\n';
  const out = injectGcodeThumbnails(bare, [block]);
  assert.ok(out.startsWith('; THUMBNAIL_BLOCK_START'), 'prepended rather than dropped into the program');
  assert.ok(out.endsWith(bare));
});

console.log(`\nG-code thumbnails: ${passed} tests passed.`);
