import assert from 'node:assert/strict';

import { formatArtifactDuration, summarizeGcodeArtifact } from '../GcodeArtifactSummary';

let passed = 0;
function test(name: string, run: () => void): void {
  run();
  passed += 1;
  console.log(`  ✓ ${name}`);
}

const ARTIFACT = [
  '; generated by OrcaXR',
  'G1 X10 Y10 E1',
  '; filament used [mm] = 4748.86, 1472.56, 0.00, 0.00',
  '; filament used [cm3] = 11.42, 3.54, 0.00, 0.00',
  '; filament used [g] = 14.16, 4.39, 0.00, 0.00',
  '; total filament used [g] = 18.56',
  '; total filament cost = 0.00',
  '; total filament change = 88',
  '; total layers count = 225',
  '; estimated printing time (normal mode) = 45m 50s',
  '; estimated first layer printing time (normal mode) = 19s',
  '',
  '; CONFIG_BLOCK_START',
  '; filament_colour = #5F605F;#E22B22;#FEC134;#FEFEFE',
  '; filament_type = PLA;PLA;PLA;PLA',
  '; CONFIG_BLOCK_END',
  '',
].join('\n');

test('reads the totals the engine wrote, per tool and overall', () => {
  const summary = summarizeGcodeArtifact(ARTIFACT);
  assert.equal(summary.empty, false);
  assert.equal(summary.perTool.length, 4);
  assert.deepEqual(summary.perTool[0], {
    toolIndex: 0,
    lengthMm: 4748.86,
    volumeCm3: 11.42,
    weightG: 14.16,
    colorHex: '#5F605F',
    material: 'PLA',
  });
  // A zero the engine stated is a real zero, not a missing value.
  assert.equal(summary.perTool[3].weightG, 0);
  assert.equal(summary.totalWeightG, 18.56);
  assert.equal(summary.totalCost, 0);
  assert.equal(summary.toolChanges, 88);
  assert.equal(summary.layerCount, 225);
  assert.equal(summary.estimatedSeconds, 45 * 60 + 50);
  assert.equal(summary.firstLayerSeconds, 19);
  assert.equal(Object.isFrozen(summary), true);
});

test('leaves out what the artifact never stated instead of reporting zero', () => {
  const sparse = summarizeGcodeArtifact(['; filament used [g] = 3.20', '; total layers count = 12', ''].join('\n'));
  assert.equal(sparse.empty, false);
  assert.deepEqual(sparse.perTool, [{ toolIndex: 0, weightG: 3.2 }]);
  assert.equal('totalWeightG' in sparse, false);
  assert.equal('estimatedSeconds' in sparse, false);
  assert.equal(sparse.layerCount, 12);

  const nothing = summarizeGcodeArtifact('G1 X1 Y1 E1\n');
  assert.equal(nothing.empty, true);
  assert.deepEqual(nothing.perTool, []);
});

test('accepts every duration shape the engine writes and rejects the rest', () => {
  const parse = (value: string) =>
    summarizeGcodeArtifact(`; estimated printing time (normal mode) = ${value}\n`).estimatedSeconds;
  assert.equal(parse('45s'), 45);
  assert.equal(parse('12m 30s'), 750);
  assert.equal(parse('1h 04m 12s'), 3852);
  assert.equal(parse('2d 3h'), 2 * 86_400 + 3 * 3600);
  assert.equal(parse('unknown'), undefined);
  assert.equal(parse('45 minutes'), undefined);
  assert.equal(parse(''), undefined);
});

test('ignores malformed numbers rather than coercing them', () => {
  const summary = summarizeGcodeArtifact(
    [
      '; filament used [mm] = 10.5, none, 3',
      '; total filament used [g] = NaN',
      '; total layers count = -4',
      '; total filament change = 2.5',
      '',
    ].join('\n'),
  );
  assert.deepEqual(
    summary.perTool.map((tool) => tool.lengthMm),
    [10.5, undefined, 3],
  );
  assert.equal('totalWeightG' in summary, false);
  assert.equal('layerCount' in summary, false, 'a negative layer count is not a count');
  assert.equal('toolChanges' in summary, false, 'a fractional change count is not a count');
});

test('reads a large artifact from its trailer without scanning the toolpaths', () => {
  const bulk = `${'G1 X1 Y1 E0.1\n'.repeat(200_000)}; total layers count = 7\n`;
  assert.ok(bulk.length > 1_000_000);
  assert.equal(summarizeGcodeArtifact(bulk).layerCount, 7);
  // A total buried far above the trailer window is deliberately not reported:
  // the engine always writes these at the end.
  const stale = `; total layers count = 999\n${'G1 X1 Y1 E0.1\n'.repeat(200_000)}`;
  assert.equal(summarizeGcodeArtifact(stale).empty, true);
});

test('formats durations for display', () => {
  assert.equal(formatArtifactDuration(undefined), '—');
  assert.equal(formatArtifactDuration(-1), '—');
  assert.equal(formatArtifactDuration(45), '45s');
  assert.equal(formatArtifactDuration(750), '12m 30s');
  assert.equal(formatArtifactDuration(3852), '1h 04m');
  assert.equal(formatArtifactDuration(2 * 86_400 + 3 * 3600), '2d 3h');
});

console.log(`\nG-code artifact summary: ${passed} tests passed.`);
