/**
 * Slicing must work on the origin this app is actually deployed on.
 *
 * The all-in-one server publishes the UI over plain HTTP on a LAN address
 * (`http://192.168.1.90:3000`), and that is not a secure context — only
 * `localhost` is special-cased into one, which is why nothing caught this
 * locally. `crypto.subtle` is therefore absent there, and every slice from
 * another machine on the network died with "Web Crypto SHA-256 is unavailable"
 * before it began.
 */
import assert from 'node:assert/strict';
import { createHash, webcrypto } from 'node:crypto';
import { Sha256SliceContentHasher } from './hash';
import { sha256Bytes } from '../../slicer/Utf8Sha256';

let passed = 0;
async function test(name: string, run: () => void | Promise<void>): Promise<void> {
  await run();
  passed += 1;
  console.log(`  ✓ ${name}`);
}

const original = Object.getOwnPropertyDescriptor(globalThis, 'crypto');
const setCrypto = (value: unknown) => Object.defineProperty(globalThis, 'crypto', { configurable: true, value });
const restore = () => {
  if (original) Object.defineProperty(globalThis, 'crypto', original);
  else Reflect.deleteProperty(globalThis, 'crypto');
};

const sample = new TextEncoder().encode('; generated by Snapmaker Orca\nG1 X1 Y2 E3\n');
const expected = `sha256:${createHash('sha256').update(sample).digest('hex')}`;

try {
  await test('an insecure origin still hashes, rather than refusing to slice', async () => {
    // Exactly what a browser exposes off a secure context: `crypto` exists,
    // `crypto.subtle` does not.
    setCrypto({ getRandomValues: (array: Uint8Array) => array });
    assert.equal(await new Sha256SliceContentHasher().digest(sample), expected);
  });

  await test('and a missing crypto object entirely is survivable too', async () => {
    setCrypto(undefined);
    assert.equal(await new Sha256SliceContentHasher().digest(sample), expected);
  });

  await test('the two paths agree, so an artifact keeps one identity across origins', async () => {
    setCrypto(webcrypto);
    const viaWebCrypto = await new Sha256SliceContentHasher().digest(sample);
    setCrypto({});
    const viaFallback = await new Sha256SliceContentHasher().digest(sample);
    assert.equal(viaWebCrypto, viaFallback);
    assert.equal(viaWebCrypto, expected);
  });

  await test('the fallback is a real SHA-256 at every block boundary', () => {
    // Padding is where a hand-written SHA-256 goes wrong: empty input, exactly
    // one block, one byte over, and a length that needs a second padding block.
    for (const length of [0, 1, 55, 56, 63, 64, 65, 119, 120, 1000, 100_003]) {
      const bytes = new Uint8Array(length).map((_, index) => (index * 31) % 251);
      assert.equal(
        sha256Bytes(bytes),
        `sha256:${createHash('sha256').update(bytes).digest('hex')}`,
        `length ${length}`,
      );
    }
  });

  await test('the digest does not consume or alter what it was given', async () => {
    setCrypto({});
    const bytes = Uint8Array.from(sample);
    await new Sha256SliceContentHasher().digest(bytes);
    assert.deepEqual(bytes, sample);
  });
} finally {
  restore();
}

console.log(`\nSlice hashing without Web Crypto: ${passed} tests passed.`);
