import assert from 'node:assert/strict';
// @ts-expect-error -- jsdom has no bundled declaration file.
import { JSDOM } from 'jsdom';
import { AiConfigDialog } from '../AiConfigDialog';
import { CommandPalette } from '../CommandPalette';
const dom = new JSDOM('<button id="trigger"></button><div id="overlay"><input><div id="list"></div></div>');
Object.assign(globalThis, { window: dom.window, document: dom.window.document });
const palette = new CommandPalette({ forSurface: () => [] } as never, {} as never, { get: () => ({}) } as never);
const overlay = document.getElementById('overlay')!;
const input = document.querySelector('input')!;
const list = document.getElementById('list')!;
const trigger = document.getElementById('trigger')!;
palette.mount(overlay, input, list, trigger);
palette.mount(overlay, input, list, trigger);
const toggle = () => window.dispatchEvent(new dom.window.KeyboardEvent('keydown', { key: 'k', ctrlKey: true }));
toggle();
assert.equal(palette.isOpen(), true, 'remount must retain exactly one Ctrl-K handler');
palette.dispose();
palette.dispose();
toggle();
trigger.click();
assert.equal(palette.isOpen(), false, 'disposed palette must release global and trigger handlers');
palette.mount(overlay, input, list, trigger);
toggle();
assert.equal(palette.isOpen(), true, 'a new mount remains usable after disposal');
palette.dispose();
AiConfigDialog.init();
const save = document.getElementById('ai-config-save')!;
AiConfigDialog.dispose();
assert.equal(document.getElementById('ai-config-dialog'), null);
assert.equal(save.onclick, null, 'detached AI controls must release their closures');
AiConfigDialog.init();
assert.equal(document.querySelectorAll('#ai-config-dialog').length, 1);
AiConfigDialog.dispose();
dom.window.close();
console.log('Command palette remount, shortcut ownership and idempotent disposal passed.');
