// Explicit test entrypoint: never included in the runtime image or server routes.
import fs from "node:fs/promises";
import http from "node:http";
import https from "node:https";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { createSlicerService } from "./server.js";

export const FIXTURE_GCODE =
  "; generated by deployment fixture\nG21\nG90\nM83\n;LAYER_CHANGE\n;Z:0.2\nG1 Z0.2\nG1 X1 Y1 E1 F900\n";

export async function startDeploymentFixture({
  webRoot,
  certDirectory,
  port = 0,
  tlsPort = 0,
  host = "127.0.0.1",
}) {
  const service = createSlicerService({
    env: {},
    webRoot,
    engine: "wasm",
    logger: { log() {}, warn() {}, error() {} },
    config: {
      host,
      trustMode: "same-origin",
      acceptLanExposure: true,
      trustedProxy: true,
      maxRequestsPerWindow: 40,
      maxSliceRequestsPerWindow: 10,
      rateWindowMs: 60_000,
    },
    runner: async ({ outputPath, onProgress, signal }) => {
      onProgress(50, "Deterministic deployment fixture");
      await new Promise((resolve, reject) => {
        const abort = () => {
          clearTimeout(timer);
          reject(signal.reason);
        };
        const timer = setTimeout(() => {
          signal.removeEventListener("abort", abort);
          resolve();
        }, 50);
        signal.addEventListener("abort", abort, { once: true });
        if (signal.aborted) abort();
      });
      await fs.writeFile(outputPath, FIXTURE_GCODE);
    },
  });
  const server = service.start(port);
  await new Promise((resolve, reject) => {
    server.once("listening", resolve);
    server.once("error", reject);
  });
  const proxy = https.createServer(
    {
      key: await fs.readFile(path.join(certDirectory, "key.pem")),
      cert: await fs.readFile(path.join(certDirectory, "cert.pem")),
    },
    (req, res) => {
      // Model the trusted TLS boundary: overwrite, never append, proxy identity.
      const headers = {
        ...req.headers,
        "x-forwarded-proto": "https",
        "tailscale-user-login": "deployment@example.test",
      };
      delete headers["x-forwarded-for"];
      delete headers["x-forwarded-host"];
      const upstream = http.request(
        {
          host: "127.0.0.1",
          port: server.address().port,
          path: req.url,
          method: req.method,
          headers,
        },
        (reply) => {
          res.writeHead(reply.statusCode, reply.headers);
          reply.pipe(res);
        },
      );
      upstream.on("error", () => {
        if (!res.headersSent) res.writeHead(502);
        res.end();
      });
      res.on("close", () => upstream.destroy());
      req.pipe(upstream);
    },
  );
  await new Promise((resolve, reject) => {
    proxy.once("error", reject);
    proxy.listen(tlsPort, host, resolve);
  });
  return {
    port: server.address().port,
    tlsPort: proxy.address().port,
    async close() {
      proxy.closeAllConnections();
      server.closeAllConnections();
      await Promise.all([
        new Promise((resolve) => proxy.close(resolve)),
        new Promise((resolve) => server.close(resolve)),
      ]);
      await service.shutdown();
    },
  };
}

if (
  process.argv[1] &&
  path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)
) {
  const fixture = await startDeploymentFixture({
    webRoot: "/app/public",
    certDirectory: "/test-certs",
    port: 3000,
    tlsPort: 3443,
    host: "0.0.0.0",
  });
  for (const event of ["SIGINT", "SIGTERM"])
    process.once(event, async () => {
      await fixture.close();
      process.exit(0);
    });
  console.log("Deployment fixture listening");
}
