import assert from "node:assert/strict";
import fs from "node:fs/promises";
import test from "node:test";
import { createSlicerService } from "./server.js";
import { loadServerConfig } from "./security.mjs";
import { modelForm, valid3mf } from "./test-helpers.mjs";

const services = new Set();

async function fixture(options = {}) {
  const base = loadServerConfig({});
  const config = {
    ...base,
    maxConcurrentJobs: 1,
    maxQueuedJobs: 1,
    maxStoredJobs: 4,
    maxRequestsPerWindow: 100,
    maxSliceRequestsPerWindow: 100,
    sliceTimeoutMs: 2000,
    queueTimeoutMs: 2000,
    childKillGraceMs: 50,
    jobTtlMs: 5000,
    ...options.config,
  };
  const runner =
    options.runner ??
    (async ({ outputPath, onProgress }) => {
      onProgress(50, "Generating G-code");
      await fs.writeFile(outputPath, "G28\n; generated by test\n");
    });
  const service = createSlicerService({
    config,
    runner,
    engine: options.engine ?? "cli",
    logger: options.logger,
  });
  const server = service.start(0);
  await new Promise((resolve, reject) => {
    server.once("listening", resolve);
    server.once("error", reject);
  });
  const address = server.address();
  const instance = {
    service,
    server,
    url: `http://127.0.0.1:${address.port}`,
    async close() {
      await service.shutdown();
      await new Promise((resolve) => server.close(resolve));
      server.closeAllConnections?.();
      services.delete(instance);
    },
  };
  services.add(instance);
  return instance;
}

async function waitForStatus(url, jobId, expected, headers = {}) {
  const deadline = Date.now() + 3000;
  for (;;) {
    const response = await fetch(`${url}/jobs/${jobId}`, { headers });
    assert.equal(response.status, 200);
    const status = await response.json();
    if (expected.includes(status.status)) return status;
    if (Date.now() > deadline)
      assert.fail(
        `Timed out waiting for ${expected}; last status ${status.status}`,
      );
    await new Promise((resolve) => setTimeout(resolve, 20));
  }
}

test.after(async () => {
  await Promise.allSettled([...services].map((instance) => instance.close()));
});

test("readiness, missing uploads, and unknown jobs use bounded public responses", async () => {
  const instance = await fixture();
  try {
    const ping = await fetch(`${instance.url}/ping`);
    assert.equal(ping.status, 200);
    assert.equal(await ping.text(), "pong");
    assert.equal(ping.headers.get("x-powered-by"), null);

    const missing = await fetch(`${instance.url}/slice`, { method: "POST" });
    assert.equal(missing.status, 400);
    assert.deepEqual(await missing.json(), {
      error: {
        code: "FILE_REQUIRED",
        message: "A model or project file is required.",
      },
    });
    const unknown = await fetch(`${instance.url}/jobs/not-a-job`);
    assert.equal(unknown.status, 404);
    assert.equal((await unknown.json()).error.code, "JOB_NOT_FOUND");
    const unknownEndpoint = await fetch(`${instance.url}/not-an-endpoint`);
    assert.equal(unknownEndpoint.status, 404);
    assert.equal((await unknownEndpoint.json()).error.code, "NOT_FOUND");
  } finally {
    await instance.close();
  }
});

test("sync and async slicing preserve G-code delivery semantics", async () => {
  const instance = await fixture();
  try {
    const sync = await fetch(`${instance.url}/slice`, {
      method: "POST",
      body: modelForm(),
    });
    assert.equal(sync.status, 200);
    assert.match(await sync.text(), /^G28/m);

    const accepted = await fetch(`${instance.url}/slice?async=1`, {
      method: "POST",
      body: modelForm(),
    });
    assert.equal(accepted.status, 202);
    const { job } = await accepted.json();
    const status = await waitForStatus(instance.url, job, ["done"]);
    assert.equal(status.percent, 100);
    const output = instance.service.jobs.get(job).outputPath;
    assert.equal((await fs.stat(output)).mode & 0o777, 0o600);
    const result = await fetch(`${instance.url}/jobs/${job}/gcode`);
    assert.equal(result.status, 200);
    assert.match(await result.text(), /generated by test/);
    assert.equal((await fetch(`${instance.url}/jobs/${job}`)).status, 404);
  } finally {
    await instance.close();
  }
});

test("CORS is exact and non-loopback service requires bearer auth", async () => {
  const token = "0123456789abcdef0123456789abcdef";
  const instance = await fixture({
    config: {
      host: "0.0.0.0",
      token,
      explicitOrigins: ["https://allowed.example"],
      maxStoredJobs: 4,
    },
  });
  try {
    const deniedOrigin = await fetch(`${instance.url}/ping`, {
      headers: {
        Origin: "https://allowed.example.evil.test",
        Authorization: `Bearer ${token}`,
      },
    });
    assert.equal(deniedOrigin.status, 403);
    assert.equal((await deniedOrigin.json()).error.code, "ORIGIN_DENIED");

    const missingAuth = await fetch(`${instance.url}/ping`);
    assert.equal(missingAuth.status, 401);
    const wrongAuth = await fetch(`${instance.url}/ping`, {
      headers: { Authorization: `Bearer ${token}x` },
    });
    assert.equal(wrongAuth.status, 401);
    const allowed = await fetch(`${instance.url}/ping`, {
      headers: {
        Origin: "https://allowed.example",
        Authorization: `Bearer ${token}`,
      },
    });
    assert.equal(allowed.status, 200);
    assert.equal(
      allowed.headers.get("access-control-allow-origin"),
      "https://allowed.example",
    );
  } finally {
    await instance.close();
  }
});

test("upload and overrides limits reject abuse before a runner starts", async () => {
  let runs = 0;
  const instance = await fixture({
    config: { maxUploadBytes: 64, maxOverridesBytes: 32 },
    runner: async () => {
      runs += 1;
    },
  });
  try {
    const large = await fetch(`${instance.url}/slice`, {
      method: "POST",
      body: modelForm(Buffer.alloc(65, 1)),
    });
    assert.equal(large.status, 413);
    assert.equal((await large.json()).error.code, "UPLOAD_LIMIT");
    const largeJson = await fetch(`${instance.url}/slice`, {
      method: "POST",
      body: modelForm(
        Buffer.from("solid x\nendsolid x"),
        JSON.stringify({ value: "x".repeat(64) }),
      ),
    });
    assert.equal(largeJson.status, 413);
    assert.equal((await largeJson.json()).error.code, "UPLOAD_LIMIT");
    const extraPart = modelForm(Buffer.from("solid x\nendsolid x"));
    extraPart.append("unexpected", "value");
    const tooManyParts = await fetch(`${instance.url}/slice`, {
      method: "POST",
      body: extraPart,
    });
    assert.equal(tooManyParts.status, 413);
    assert.equal((await tooManyParts.json()).error.code, "UPLOAD_LIMIT");
    const oversizedJson = await fetch(`${instance.url}/slice`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ value: "x".repeat(64) }),
    });
    assert.equal(oversizedJson.status, 413);
    assert.equal((await oversizedJson.json()).error.code, "JSON_LIMIT");
    assert.equal(runs, 0);
  } finally {
    await instance.close();
  }
});

test("invalid JSON and engine failures never expose parser, path, or secret details", async () => {
  const invalidInstance = await fixture();
  try {
    const invalid = await fetch(`${invalidInstance.url}/slice`, {
      method: "POST",
      body: modelForm(undefined, "{"),
    });
    assert.equal(invalid.status, 400);
    const invalidText = await invalid.text();
    assert.match(invalidText, /Overrides must be valid JSON/);
    assert.doesNotMatch(invalidText, /Unexpected end|position \d/);
  } finally {
    await invalidInstance.close();
  }

  const logLines = [];
  const failedInstance = await fixture({
    runner: async () => {
      throw new Error("secret-token at /tmp/private/model.stl");
    },
    logger: {
      log: () => {},
      error: (...parts) => logLines.push(parts.join(" ")),
    },
  });
  try {
    const failed = await fetch(`${failedInstance.url}/slice`, {
      method: "POST",
      body: modelForm(),
    });
    assert.equal(failed.status, 500);
    const text = await failed.text();
    assert.match(text, /SLICE_FAILED/);
    assert.doesNotMatch(text, /secret-token|private\/model/);
    assert.match(logLines.join("\n"), /Error \[UNCLASSIFIED\]/);
    assert.doesNotMatch(logLines.join("\n"), /secret-token|private\/model/);
  } finally {
    await failedInstance.close();
  }
});

test("queue and stored-job bounds reject excess work", async () => {
  const releases = [];
  const runner = ({ outputPath, signal }) =>
    new Promise((resolve, reject) => {
      const release = async () => {
        await fs.writeFile(outputPath, "G28\n");
        resolve();
      };
      releases.push(release);
      signal.addEventListener("abort", () => reject(signal.reason), {
        once: true,
      });
    });
  const instance = await fixture({
    config: { maxConcurrentJobs: 1, maxQueuedJobs: 1, maxStoredJobs: 2 },
    runner,
  });
  try {
    const first = await fetch(`${instance.url}/slice?async=1`, {
      method: "POST",
      body: modelForm(),
    });
    const second = await fetch(`${instance.url}/slice?async=1`, {
      method: "POST",
      body: modelForm(),
    });
    assert.equal(first.status, 202);
    assert.equal(second.status, 202);
    const third = await fetch(`${instance.url}/slice?async=1`, {
      method: "POST",
      body: modelForm(),
    });
    assert.equal(third.status, 503);
    assert.equal((await third.json()).error.code, "SERVER_BUSY");
    await releases[0]();
    const firstId = (await first.json()).job;
    await waitForStatus(instance.url, firstId, ["done"]);
  } finally {
    await instance.close();
  }
});

test("DELETE cancels a running job and timeout aborts an unresponsive slice", async () => {
  let abortObserved = false;
  const blockingRunner = ({ signal }) =>
    new Promise((resolve, reject) => {
      signal.addEventListener(
        "abort",
        () => {
          abortObserved = true;
          reject(signal.reason);
        },
        { once: true },
      );
    });
  const cancelledInstance = await fixture({ runner: blockingRunner });
  try {
    const accepted = await fetch(`${cancelledInstance.url}/slice?async=1`, {
      method: "POST",
      body: modelForm(),
    });
    const { job } = await accepted.json();
    await waitForStatus(cancelledInstance.url, job, ["running"]);
    const cancelled = await fetch(`${cancelledInstance.url}/jobs/${job}`, {
      method: "DELETE",
    });
    assert.equal(cancelled.status, 202);
    const status = await waitForStatus(cancelledInstance.url, job, [
      "cancelled",
    ]);
    assert.equal(status.errorCode, "SLICE_CANCELLED");
    assert.equal(abortObserved, true);
  } finally {
    await cancelledInstance.close();
  }

  const timeoutInstance = await fixture({
    config: { sliceTimeoutMs: 100 },
    runner: blockingRunner,
  });
  try {
    const accepted = await fetch(`${timeoutInstance.url}/slice?async=1`, {
      method: "POST",
      body: modelForm(),
    });
    const { job } = await accepted.json();
    const status = await waitForStatus(timeoutInstance.url, job, ["error"]);
    assert.equal(status.errorCode, "SLICE_TIMEOUT");
    assert.doesNotMatch(JSON.stringify(status), /private|secret/);
  } finally {
    await timeoutInstance.close();
  }
});

test("queued jobs can be cancelled and expire without starting a runner", async () => {
  let runs = 0;
  const blockingRunner = ({ signal }) =>
    new Promise((resolve, reject) => {
      runs += 1;
      signal.addEventListener("abort", () => reject(signal.reason), {
        once: true,
      });
    });
  const cancelledInstance = await fixture({ runner: blockingRunner });
  try {
    const first = await fetch(`${cancelledInstance.url}/slice?async=1`, {
      method: "POST",
      body: modelForm(),
    });
    const second = await fetch(`${cancelledInstance.url}/slice?async=1`, {
      method: "POST",
      body: modelForm(),
    });
    const firstId = (await first.json()).job;
    const secondId = (await second.json()).job;
    await waitForStatus(cancelledInstance.url, secondId, ["queued"]);
    const cancelled = await fetch(`${cancelledInstance.url}/jobs/${secondId}`, {
      method: "DELETE",
    });
    assert.equal(cancelled.status, 200);
    assert.equal(
      (await waitForStatus(cancelledInstance.url, secondId, ["cancelled"]))
        .errorCode,
      "SLICE_CANCELLED",
    );
    assert.equal(runs, 1);
    await fetch(`${cancelledInstance.url}/jobs/${firstId}`, {
      method: "DELETE",
    });
  } finally {
    await cancelledInstance.close();
  }

  const expiredInstance = await fixture({
    config: { queueTimeoutMs: 100 },
    runner: blockingRunner,
  });
  try {
    const first = await fetch(`${expiredInstance.url}/slice?async=1`, {
      method: "POST",
      body: modelForm(),
    });
    const second = await fetch(`${expiredInstance.url}/slice?async=1`, {
      method: "POST",
      body: modelForm(),
    });
    const firstId = (await first.json()).job;
    const secondId = (await second.json()).job;
    const status = await waitForStatus(expiredInstance.url, secondId, [
      "error",
    ]);
    assert.equal(status.errorCode, "QUEUE_TIMEOUT");
    assert.equal(runs, 2);
    await fetch(`${expiredInstance.url}/jobs/${firstId}`, { method: "DELETE" });
  } finally {
    await expiredInstance.close();
  }
});

test("3MF traversal is rejected before slicing", async () => {
  let runs = 0;
  const malicious = valid3mf([{ name: "../outside", data: "bad" }]);
  const instance = await fixture({
    runner: async () => {
      runs += 1;
    },
  });
  try {
    const response = await fetch(`${instance.url}/slice`, {
      method: "POST",
      body: modelForm(malicious, "{}", "project.3mf"),
    });
    assert.equal(response.status, 400);
    assert.equal((await response.json()).error.code, "INVALID_3MF");
    assert.equal(runs, 0);
  } finally {
    await instance.close();
  }
});

test("rate limits return 429 with Retry-After", async () => {
  const instance = await fixture({ config: { maxRequestsPerWindow: 1 } });
  try {
    assert.equal((await fetch(`${instance.url}/ping`)).status, 200);
    const denied = await fetch(`${instance.url}/ping`);
    assert.equal(denied.status, 429);
    assert(Number(denied.headers.get("retry-after")) >= 1);
  } finally {
    await instance.close();
  }

  const preflightInstance = await fixture({
    config: { maxRequestsPerWindow: 1 },
  });
  try {
    const headers = {
      Origin: "http://localhost:5173",
      "Access-Control-Request-Method": "GET",
    };
    assert.equal(
      (
        await fetch(`${preflightInstance.url}/ping`, {
          method: "OPTIONS",
          headers,
        })
      ).status,
      204,
    );
    assert.equal(
      (
        await fetch(`${preflightInstance.url}/ping`, {
          method: "OPTIONS",
          headers,
        })
      ).status,
      429,
    );
  } finally {
    await preflightInstance.close();
  }
});
