import assert from "node:assert/strict";
import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import { createSlicerService } from "./server.js";
import { loadServerConfig } from "./security.mjs";
import { modelForm, valid3mf } from "./test-helpers.mjs";

const services = new Set();

async function fixture(options = {}) {
  const base = loadServerConfig({});
  const config = {
    ...base,
    maxConcurrentJobs: 1,
    maxQueuedJobs: 1,
    maxStoredJobs: 4,
    maxRequestsPerWindow: 100,
    maxSliceRequestsPerWindow: 100,
    sliceTimeoutMs: 2000,
    queueTimeoutMs: 2000,
    childKillGraceMs: 50,
    jobTtlMs: 5000,
    ...options.config,
  };
  const runner =
    options.runner ??
    (async ({ outputPath, onProgress }) => {
      onProgress(50, "Generating G-code");
      await fs.writeFile(outputPath, "G28\n; generated by test\n");
    });
  const service = createSlicerService({
    config,
    runner,
    engine: options.engine ?? "cli",
    logger: options.logger,
  });
  const server = service.start(0);
  await new Promise((resolve, reject) => {
    server.once("listening", resolve);
    server.once("error", reject);
  });
  const address = server.address();
  const instance = {
    service,
    server,
    url: `http://127.0.0.1:${address.port}`,
    async close() {
      await service.shutdown();
      await new Promise((resolve) => server.close(resolve));
      server.closeAllConnections?.();
      services.delete(instance);
    },
  };
  services.add(instance);
  return instance;
}

async function waitForStatus(url, jobId, expected, headers = {}) {
  const deadline = Date.now() + 3000;
  for (;;) {
    const response = await fetch(`${url}/jobs/${jobId}`, { headers });
    assert.equal(response.status, 200);
    const status = await response.json();
    if (expected.includes(status.status)) return status;
    if (Date.now() > deadline)
      assert.fail(
        `Timed out waiting for ${expected}; last status ${status.status}`,
      );
    await new Promise((resolve) => setTimeout(resolve, 20));
  }
}

test.after(async () => {
  await Promise.allSettled([...services].map((instance) => instance.close()));
});

test("readiness, missing uploads, and unknown jobs use bounded public responses", async () => {
  const instance = await fixture();
  try {
    const ping = await fetch(`${instance.url}/ping`);
    assert.equal(ping.status, 200);
    assert.equal(await ping.text(), "pong");
    assert.equal(ping.headers.get("x-powered-by"), null);

    const missing = await fetch(`${instance.url}/slice`, { method: "POST" });
    assert.equal(missing.status, 400);
    assert.deepEqual(await missing.json(), {
      error: {
        code: "FILE_REQUIRED",
        message: "A model or project file is required.",
      },
    });
    const unknown = await fetch(`${instance.url}/jobs/not-a-job`);
    assert.equal(unknown.status, 404);
    assert.equal((await unknown.json()).error.code, "JOB_NOT_FOUND");
    const unknownEndpoint = await fetch(`${instance.url}/not-an-endpoint`);
    assert.equal(unknownEndpoint.status, 404);
    assert.equal((await unknownEndpoint.json()).error.code, "NOT_FOUND");
  } finally {
    await instance.close();
  }
});

test("sync and async slicing preserve G-code delivery semantics", async () => {
  const instance = await fixture();
  try {
    const sync = await fetch(`${instance.url}/slice`, {
      method: "POST",
      body: modelForm(),
    });
    assert.equal(sync.status, 200);
    assert.match(await sync.text(), /^G28/m);

    const accepted = await fetch(`${instance.url}/slice?async=1`, {
      method: "POST",
      body: modelForm(),
    });
    assert.equal(accepted.status, 202);
    const { job } = await accepted.json();
    const status = await waitForStatus(instance.url, job, ["done"]);
    assert.equal(status.percent, 100);
    const output = instance.service.jobs.get(job).outputPath;
    assert.equal((await fs.stat(output)).mode & 0o777, 0o600);
    const result = await fetch(`${instance.url}/jobs/${job}/gcode`);
    assert.equal(result.status, 200);
    assert.match(await result.text(), /generated by test/);
    assert.equal((await fetch(`${instance.url}/jobs/${job}`)).status, 404);
  } finally {
    await instance.close();
  }
});

test("CORS is exact and non-loopback service requires bearer auth", async () => {
  const token = "test-only-token-00000000000000000";
  const instance = await fixture({
    config: {
      host: "0.0.0.0",
      token,
      explicitOrigins: ["https://allowed.example"],
      maxStoredJobs: 4,
    },
  });
  try {
    const deniedOrigin = await fetch(`${instance.url}/ping`, {
      headers: {
        Origin: "https://allowed.example.evil.test",
        Authorization: `Bearer ${token}`,
      },
    });
    assert.equal(deniedOrigin.status, 403);
    assert.equal((await deniedOrigin.json()).error.code, "ORIGIN_DENIED");

    const missingAuth = await fetch(`${instance.url}/ping`);
    assert.equal(missingAuth.status, 401);
    const wrongAuth = await fetch(`${instance.url}/ping`, {
      headers: { Authorization: `Bearer ${token}x` },
    });
    assert.equal(wrongAuth.status, 401);
    const allowed = await fetch(`${instance.url}/ping`, {
      headers: {
        Origin: "https://allowed.example",
        Authorization: `Bearer ${token}`,
      },
    });
    assert.equal(allowed.status, 200);
    assert.equal(
      allowed.headers.get("access-control-allow-origin"),
      "https://allowed.example",
    );
  } finally {
    await instance.close();
  }
});

test("upload and overrides limits reject abuse before a runner starts", async () => {
  let runs = 0;
  const instance = await fixture({
    config: { maxUploadBytes: 64, maxOverridesBytes: 32 },
    runner: async () => {
      runs += 1;
    },
  });
  try {
    const large = await fetch(`${instance.url}/slice`, {
      method: "POST",
      body: modelForm(Buffer.alloc(65, 1)),
    });
    assert.equal(large.status, 413);
    assert.equal((await large.json()).error.code, "UPLOAD_LIMIT");
    const largeJson = await fetch(`${instance.url}/slice`, {
      method: "POST",
      body: modelForm(
        Buffer.from("solid x\nendsolid x"),
        JSON.stringify({ value: "x".repeat(64) }),
      ),
    });
    assert.equal(largeJson.status, 413);
    assert.equal((await largeJson.json()).error.code, "UPLOAD_LIMIT");
    const extraPart = modelForm(Buffer.from("solid x\nendsolid x"));
    extraPart.append("unexpected", "value");
    const tooManyParts = await fetch(`${instance.url}/slice`, {
      method: "POST",
      body: extraPart,
    });
    assert.equal(tooManyParts.status, 413);
    assert.equal((await tooManyParts.json()).error.code, "UPLOAD_LIMIT");
    const oversizedJson = await fetch(`${instance.url}/slice`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ value: "x".repeat(64) }),
    });
    assert.equal(oversizedJson.status, 413);
    assert.equal((await oversizedJson.json()).error.code, "JSON_LIMIT");
    assert.equal(runs, 0);
  } finally {
    await instance.close();
  }
});

test("invalid JSON and engine failures never expose parser, path, or secret details", async () => {
  const invalidInstance = await fixture();
  try {
    const invalid = await fetch(`${invalidInstance.url}/slice`, {
      method: "POST",
      body: modelForm(undefined, "{"),
    });
    assert.equal(invalid.status, 400);
    const invalidText = await invalid.text();
    assert.match(invalidText, /Overrides must be valid JSON/);
    assert.doesNotMatch(invalidText, /Unexpected end|position \d/);
  } finally {
    await invalidInstance.close();
  }

  const logLines = [];
  const failedInstance = await fixture({
    runner: async () => {
      throw new Error("secret-token at /tmp/private/model.stl");
    },
    logger: {
      log: () => {},
      error: (...parts) => logLines.push(parts.join(" ")),
    },
  });
  try {
    const failed = await fetch(`${failedInstance.url}/slice`, {
      method: "POST",
      body: modelForm(),
    });
    assert.equal(failed.status, 500);
    const text = await failed.text();
    assert.match(text, /SLICE_FAILED/);
    assert.doesNotMatch(text, /secret-token|private\/model/);
    assert.match(logLines.join("\n"), /Error \[UNCLASSIFIED\]/);
    assert.doesNotMatch(logLines.join("\n"), /secret-token|private\/model/);
  } finally {
    await failedInstance.close();
  }
});

test("queue and stored-job bounds reject excess work", async () => {
  const releases = [];
  const runner = ({ outputPath, signal }) =>
    new Promise((resolve, reject) => {
      const release = async () => {
        await fs.writeFile(outputPath, "G28\n");
        resolve();
      };
      releases.push(release);
      signal.addEventListener("abort", () => reject(signal.reason), {
        once: true,
      });
    });
  const instance = await fixture({
    config: { maxConcurrentJobs: 1, maxQueuedJobs: 1, maxStoredJobs: 2 },
    runner,
  });
  try {
    const first = await fetch(`${instance.url}/slice?async=1`, {
      method: "POST",
      body: modelForm(),
    });
    const second = await fetch(`${instance.url}/slice?async=1`, {
      method: "POST",
      body: modelForm(),
    });
    assert.equal(first.status, 202);
    assert.equal(second.status, 202);
    const third = await fetch(`${instance.url}/slice?async=1`, {
      method: "POST",
      body: modelForm(),
    });
    assert.equal(third.status, 503);
    assert.equal((await third.json()).error.code, "SERVER_BUSY");
    await releases[0]();
    const firstId = (await first.json()).job;
    await waitForStatus(instance.url, firstId, ["done"]);
  } finally {
    await instance.close();
  }
});

test("DELETE cancels a running job and timeout aborts an unresponsive slice", async () => {
  let abortObserved = false;
  const blockingRunner = ({ signal }) =>
    new Promise((resolve, reject) => {
      signal.addEventListener(
        "abort",
        () => {
          abortObserved = true;
          reject(signal.reason);
        },
        { once: true },
      );
    });
  const cancelledInstance = await fixture({ runner: blockingRunner });
  try {
    const accepted = await fetch(`${cancelledInstance.url}/slice?async=1`, {
      method: "POST",
      body: modelForm(),
    });
    const { job } = await accepted.json();
    await waitForStatus(cancelledInstance.url, job, ["running"]);
    const cancelled = await fetch(`${cancelledInstance.url}/jobs/${job}`, {
      method: "DELETE",
    });
    assert.equal(cancelled.status, 202);
    const status = await waitForStatus(cancelledInstance.url, job, [
      "cancelled",
    ]);
    assert.equal(status.errorCode, "SLICE_CANCELLED");
    assert.equal(abortObserved, true);
  } finally {
    await cancelledInstance.close();
  }

  const timeoutInstance = await fixture({
    config: { sliceTimeoutMs: 100 },
    runner: blockingRunner,
  });
  try {
    const accepted = await fetch(`${timeoutInstance.url}/slice?async=1`, {
      method: "POST",
      body: modelForm(),
    });
    const { job } = await accepted.json();
    const status = await waitForStatus(timeoutInstance.url, job, ["error"]);
    assert.equal(status.errorCode, "SLICE_TIMEOUT");
    assert.doesNotMatch(JSON.stringify(status), /private|secret/);
  } finally {
    await timeoutInstance.close();
  }
});

test("queued jobs can be cancelled and expire without starting a runner", async () => {
  let runs = 0;
  const blockingRunner = ({ signal }) =>
    new Promise((resolve, reject) => {
      runs += 1;
      signal.addEventListener("abort", () => reject(signal.reason), {
        once: true,
      });
    });
  const cancelledInstance = await fixture({ runner: blockingRunner });
  try {
    const first = await fetch(`${cancelledInstance.url}/slice?async=1`, {
      method: "POST",
      body: modelForm(),
    });
    const second = await fetch(`${cancelledInstance.url}/slice?async=1`, {
      method: "POST",
      body: modelForm(),
    });
    const firstId = (await first.json()).job;
    const secondId = (await second.json()).job;
    await waitForStatus(cancelledInstance.url, secondId, ["queued"]);
    const cancelled = await fetch(`${cancelledInstance.url}/jobs/${secondId}`, {
      method: "DELETE",
    });
    assert.equal(cancelled.status, 200);
    assert.equal(
      (await waitForStatus(cancelledInstance.url, secondId, ["cancelled"]))
        .errorCode,
      "SLICE_CANCELLED",
    );
    assert.equal(runs, 1);
    await fetch(`${cancelledInstance.url}/jobs/${firstId}`, {
      method: "DELETE",
    });
  } finally {
    await cancelledInstance.close();
  }

  const expiredInstance = await fixture({
    config: { queueTimeoutMs: 100 },
    runner: blockingRunner,
  });
  try {
    const first = await fetch(`${expiredInstance.url}/slice?async=1`, {
      method: "POST",
      body: modelForm(),
    });
    const second = await fetch(`${expiredInstance.url}/slice?async=1`, {
      method: "POST",
      body: modelForm(),
    });
    const firstId = (await first.json()).job;
    const secondId = (await second.json()).job;
    const status = await waitForStatus(expiredInstance.url, secondId, [
      "error",
    ]);
    assert.equal(status.errorCode, "QUEUE_TIMEOUT");
    assert.equal(runs, 2);
    await fetch(`${expiredInstance.url}/jobs/${firstId}`, { method: "DELETE" });
  } finally {
    await expiredInstance.close();
  }
});

test("3MF traversal is rejected before slicing", async () => {
  let runs = 0;
  const malicious = valid3mf([{ name: "../outside", data: "bad" }]);
  const instance = await fixture({
    runner: async () => {
      runs += 1;
    },
  });
  try {
    const response = await fetch(`${instance.url}/slice`, {
      method: "POST",
      body: modelForm(malicious, "{}", "project.3mf"),
    });
    assert.equal(response.status, 400);
    assert.equal((await response.json()).error.code, "INVALID_3MF");
    assert.equal(runs, 0);
  } finally {
    await instance.close();
  }
});

test("rate limits return 429 with Retry-After", async () => {
  const instance = await fixture({ config: { maxRequestsPerWindow: 1 } });
  try {
    assert.equal((await fetch(`${instance.url}/ping`)).status, 200);
    const denied = await fetch(`${instance.url}/ping`);
    assert.equal(denied.status, 429);
    assert(Number(denied.headers.get("retry-after")) >= 1);
  } finally {
    await instance.close();
  }

  const preflightInstance = await fixture({
    config: { maxRequestsPerWindow: 1 },
  });
  try {
    const headers = {
      Origin: "http://localhost:5173",
      "Access-Control-Request-Method": "GET",
    };
    assert.equal(
      (
        await fetch(`${preflightInstance.url}/ping`, {
          method: "OPTIONS",
          headers,
        })
      ).status,
      204,
    );
    assert.equal(
      (
        await fetch(`${preflightInstance.url}/ping`, {
          method: "OPTIONS",
          headers,
        })
      ).status,
      429,
    );
  } finally {
    await preflightInstance.close();
  }
});

test("Web UI static serving, cache headers, and SPA fallback", async () => {
  const tempWebRoot = await fs.mkdtemp(path.join(os.tmpdir(), "orcaxr-web-test-"));
  const assetsDir = path.join(tempWebRoot, "assets");
  await fs.mkdir(assetsDir, { recursive: true });

  const indexContent = "<!DOCTYPE html><html><head><title>OrcaXR</title></head><body>OrcaXR App</body></html>";
  const jsContent = "console.log('test-asset');";
  const swContent = "self.addEventListener('install', () => {});";
  const manifestContent = '{"name":"OrcaXR"}';

  await fs.writeFile(path.join(tempWebRoot, "index.html"), indexContent);
  await fs.writeFile(path.join(tempWebRoot, "sw.js"), swContent);
  await fs.writeFile(path.join(tempWebRoot, "manifest.webmanifest"), manifestContent);
  await fs.writeFile(path.join(assetsDir, "index-D1234567.js"), jsContent);

  const prevWebRoot = process.env.ORCAXR_WEB_ROOT;
  process.env.ORCAXR_WEB_ROOT = tempWebRoot;

  let instance;
  try {
    instance = await fixture({
      config: {
        trustMode: "same-origin",
      },
    });

    // 1. Root index.html document request
    const rootRes = await fetch(`${instance.url}/`, {
      headers: { Accept: "text/html" },
    });
    assert.equal(rootRes.status, 200);
    assert.equal(await rootRes.text(), indexContent);
    assert.equal(rootRes.headers.get("cache-control"), "no-cache");
    assert.equal(rootRes.headers.get("cross-origin-opener-policy"), "same-origin");
    assert.equal(rootRes.headers.get("cross-origin-embedder-policy"), "credentialless");

    // 2. Content-hashed asset gets immutable cache
    const assetRes = await fetch(`${instance.url}/assets/index-D1234567.js`);
    assert.equal(assetRes.status, 200);
    assert.equal(await assetRes.text(), jsContent);
    assert.equal(assetRes.headers.get("cache-control"), "public, max-age=31536000, immutable");
    assert.equal(assetRes.headers.get("cross-origin-opener-policy"), "same-origin");

    // 3. Unhashed assets get no-cache
    const swRes = await fetch(`${instance.url}/sw.js`);
    assert.equal(swRes.status, 200);
    assert.equal(await swRes.text(), swContent);
    assert.equal(swRes.headers.get("cache-control"), "no-cache");

    const manifestRes = await fetch(`${instance.url}/manifest.webmanifest`);
    assert.equal(manifestRes.status, 200);
    assert.equal(await manifestRes.text(), manifestContent);
    assert.equal(manifestRes.headers.get("cache-control"), "no-cache");

    // 4. SPA fallback for HTML client navigation
    const spaRes = await fetch(`${instance.url}/plates/1`, {
      headers: { Accept: "text/html,application/xhtml+xml" },
    });
    assert.equal(spaRes.status, 200);
    assert.equal(await spaRes.text(), indexContent);
    assert.equal(spaRes.headers.get("cache-control"), "no-cache");

    // 5. Non-HTML unknown route returns JSON 404
    const apiNotFound = await fetch(`${instance.url}/unknown/api`, {
      headers: { Accept: "application/json" },
    });
    assert.equal(apiNotFound.status, 404);
    assert.equal((await apiNotFound.json()).error.code, "NOT_FOUND");

    // 6. Missing asset with extension returns 404, not index.html
    const missingAsset = await fetch(`${instance.url}/assets/missing.png`, {
      headers: { Accept: "text/html,image/png" },
    });
    assert.equal(missingAsset.status, 404);

    // 7. Unknown job ID does NOT return HTML SPA fallback
    const jobNotFound = await fetch(`${instance.url}/jobs/00000000-0000-0000-0000-000000000000`, {
      headers: { Accept: "text/html" },
    });
    assert.equal(jobNotFound.status, 404);
    assert.equal((await jobNotFound.json()).error.code, "JOB_NOT_FOUND");
  } finally {
    if (instance) await instance.close();
    if (prevWebRoot !== undefined) process.env.ORCAXR_WEB_ROOT = prevWebRoot;
    else delete process.env.ORCAXR_WEB_ROOT;
    await fs.rm(tempWebRoot, { recursive: true, force: true });
  }
});

test("same-origin trust allows browser slicing without bearer token and denies forge attempts", async () => {
  const instance = await fixture({
    config: {
      trustMode: "same-origin",
    },
  });

  const validModel = valid3mf();

  try {
    // 1. Same-origin browser slice (matching Origin + sec-fetch-site) succeeds without token
    const originHeaders = {
      Origin: instance.url,
      "Sec-Fetch-Site": "same-origin",
    };
    const browserSlice = await fetch(`${instance.url}/slice`, {
      method: "POST",
      headers: originHeaders,
      body: modelForm(validModel, "{}", "project.3mf"),
    });
    assert.equal(browserSlice.status, 200);

    // 2. Non-browser POST with missing Origin gets 401 AUTH_REQUIRED
    const nonBrowserSlice = await fetch(`${instance.url}/slice`, {
      method: "POST",
      body: modelForm(validModel, "{}", "project.3mf"),
    });
    assert.equal(nonBrowserSlice.status, 401);
    assert.equal((await nonBrowserSlice.json()).error.code, "AUTH_REQUIRED");

    // 3. Cross-origin browser POST with foreign Origin gets 403 ORIGIN_DENIED
    const foreignSlice = await fetch(`${instance.url}/slice`, {
      method: "POST",
      headers: {
        Origin: "http://malicious.example.com",
        "Sec-Fetch-Site": "cross-site",
      },
      body: modelForm(validModel, "{}", "project.3mf"),
    });
    assert.equal(foreignSlice.status, 403);
    assert.equal((await foreignSlice.json()).error.code, "ORIGIN_DENIED");

    // 4. Non-browser POST with Bearer token succeeds
    const tokenSlice = await fetch(`${instance.url}/slice`, {
      method: "POST",
      headers: {
        Authorization: `Bearer ${instance.service.config.token}`,
      },
      body: modelForm(validModel, "{}", "project.3mf"),
    });
    assert.equal(tokenSlice.status, 200);
  } finally {
    await instance.close();
  }
});

test("trusted proxy rate-limits by Tailscale-User-Login header", async () => {
  const instance = await fixture({
    config: {
      maxRequestsPerWindow: 1,
      trustedProxy: true,
      trustMode: "same-origin",
    },
  });

  try {
    const originHeaders = {
      Origin: instance.url,
      "Sec-Fetch-Site": "same-origin",
    };

    // User Alice: first request ok, second 429
    const alice1 = await fetch(`${instance.url}/ping`, {
      headers: { ...originHeaders, "Tailscale-User-Login": "alice@tailnet" },
    });
    assert.equal(alice1.status, 200);

    const alice2 = await fetch(`${instance.url}/ping`, {
      headers: { ...originHeaders, "Tailscale-User-Login": "alice@tailnet" },
    });
    assert.equal(alice2.status, 429);

    // User Bob: independent bucket, first request ok
    const bob1 = await fetch(`${instance.url}/ping`, {
      headers: { ...originHeaders, "Tailscale-User-Login": "bob@tailnet" },
    });
    assert.equal(bob1.status, 200);

    const bob2 = await fetch(`${instance.url}/ping`, {
      headers: { ...originHeaders, "Tailscale-User-Login": "bob@tailnet" },
    });
    assert.equal(bob2.status, 429);
  } finally {
    await instance.close();
  }
});
