/**
 * The stock primitives, at upstream's own dimensions (P5.8, P11.2).
 *
 * Three of upstream's six were missing here — cone, disc, and torus — and the
 * three that existed were built inline in the XR workspace, where nothing could
 * check them. Both problems have the same fix: the shapes are generated by a
 * module that imports geometry and nothing else, so what an operator gets can
 * be measured without a browser.
 *
 * The dimensions are upstream's, read from `GUI_ObjectList.cpp::create_mesh`
 * with its `side` at the 20 mm this app already uses for a cube. That is what
 * parity means here — a disc is 0.2 mm thick because upstream's disc is a
 * cylinder of literal height 0.2, not a fifth of anything — while the
 * tessellation is deliberately ours: upstream's torus is 120 × 120 segments
 * (28,800 triangles) for a 20 mm decoration, and the shape is what the operator
 * prints, not the triangle count.
 *
 * Every shape is authored in the printer's frame, Z up, so the caller does not
 * have to know which axis a generator happened to prefer.
 */

import * as THREE from 'three';

export type PrimitiveKind = 'cube' | 'cylinder' | 'sphere' | 'cone' | 'disc' | 'torus';

/** Upstream's `side`: the cube's edge, and the base for every other shape. */
export const PRIMITIVE_SIDE_MM = 20;

export const PRIMITIVE_KINDS: readonly PrimitiveKind[] = Object.freeze([
  'cube',
  'cylinder',
  'sphere',
  'cone',
  'disc',
  'torus',
]);

/** What each primitive is, in the words a menu entry uses. */
export const PRIMITIVE_DESCRIPTIONS: Readonly<Record<PrimitiveKind, string>> = Object.freeze({
  cube: `Add a ${PRIMITIVE_SIDE_MM} mm cube`,
  cylinder: `Add a ${PRIMITIVE_SIDE_MM} mm cylinder`,
  sphere: `Add a ${PRIMITIVE_SIDE_MM} mm sphere`,
  cone: `Add a ${PRIMITIVE_SIDE_MM} mm cone`,
  disc: `Add a ${PRIMITIVE_SIDE_MM} mm disc, 0.2 mm thick`,
  torus: `Add a ${PRIMITIVE_SIDE_MM} mm torus`,
});

/**
 * One stock primitive, Z up, centred on the origin in X and Y.
 *
 * Returned non-indexed because every consumer here — the mesh codec, the paint
 * annotations, the BVH — addresses triangles rather than vertices, and an
 * indexed buffer would have to be expanded at the first of them anyway.
 */
export function primitiveGeometry(kind: PrimitiveKind, side = PRIMITIVE_SIDE_MM): THREE.BufferGeometry {
  const radius = 0.5 * side;
  let geometry: THREE.BufferGeometry;
  switch (kind) {
    case 'cylinder':
      geometry = new THREE.CylinderGeometry(radius, radius, side, 48);
      geometry.rotateX(Math.PI / 2); // axis Y → printer Z
      break;
    case 'sphere':
      geometry = new THREE.SphereGeometry(radius, 48, 32);
      break;
    case 'cone':
      // Base down, apex up: upstream builds it from z = 0 to z = h, and a cone
      // resting on its point is not a thing anyone asked for.
      geometry = new THREE.ConeGeometry(radius, side, 48);
      geometry.rotateX(Math.PI / 2);
      break;
    case 'disc':
      // 0.2 mm is upstream's literal, not a proportion. A disc scaled with the
      // side would be a short cylinder, which upstream already offers.
      geometry = new THREE.CylinderGeometry(radius, radius, 0.2, 48);
      geometry.rotateX(Math.PI / 2);
      break;
    case 'torus':
      // Upstream: major radius 0.5 × side, tube radius 0.125 × side. Three's
      // torus already lies in the XY plane with its hole along Z, which is the
      // printer's up, so it needs no rotation — it lies flat on the bed.
      geometry = new THREE.TorusGeometry(radius, 0.125 * side, 32, 96);
      break;
    default:
      geometry = new THREE.BoxGeometry(side, side, side);
  }
  return geometry.toNonIndexed();
}

/** The file name a generated primitive is imported under. */
export function primitiveFileName(kind: PrimitiveKind): string {
  return `${kind}.stl`;
}
