package dev.orcaxr.app.mcp

import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import android.util.Base64
import android.util.Log
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/**
 * Audit H3 (2026-05-07) — symmetric AEAD wrapper for at-rest secrets
 * persisted to DataStore (the Anthropic API key today; the MCP bearer
 * token is a follow-up). Two implementations:
 *
 * - [AndroidKeystoreSecretBox] — AES-256-GCM with a key held in the
 *   Android Keystore. The key never leaves the secure-element-backed
 *   keystore (TEE on most Android devices, hardware-backed StrongBox
 *   on supported ones). The plaintext is decrypted only inside the
 *   process at read time.
 * - [PlaintextSecretBox] — pass-through, for unit tests that don't
 *   have a Keystore. Production code never instantiates it.
 *
 * The on-disk format is `base64( 12-byte IV || ciphertext+tag )`.
 * Migration from plaintext: [decrypt] returns the original string when
 * the input doesn't decode as our encrypted format, so an existing
 * install whose key was previously stored as plaintext keeps working
 * until the next write — at which point the value is re-encrypted.
 */
interface SecretBox {
    fun encrypt(plaintext: String): String
    /** Returns null when the input can't be decoded by this box. */
    fun decrypt(encoded: String): String?
}

/**
 * Audit H3 — AES-256-GCM via the Android Keystore. Key alias is
 * versioned ("orcaxr_secret_v1") so a future cipher change can
 * coexist with old ciphertext during a migration window.
 *
 * Keystore behavior we depend on:
 * - `KeyGenerator.getInstance(AES, "AndroidKeyStore")` returns a key
 *   handle, not the raw bytes — we cannot extract the AES material.
 * - `AES_GCM_NOPADDING` is supported on API 23+ (we ship minSdk 31).
 * - The IV is generated by the cipher (Keystore policy) and exposed
 *   via `cipher.iv` after `init(ENCRYPT_MODE, key)` succeeds.
 */
class AndroidKeystoreSecretBox(
    private val keyAlias: String = DEFAULT_KEY_ALIAS,
) : SecretBox {

    override fun encrypt(plaintext: String): String {
        val key = getOrCreateKey()
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.ENCRYPT_MODE, key)
        val iv = cipher.iv  // Keystore allocated; 12 bytes for GCM
        val ct = cipher.doFinal(plaintext.toByteArray(Charsets.UTF_8))
        val out = ByteArray(iv.size + ct.size)
        System.arraycopy(iv, 0, out, 0, iv.size)
        System.arraycopy(ct, 0, out, iv.size, ct.size)
        return Base64.encodeToString(out, Base64.NO_WRAP)
    }

    override fun decrypt(encoded: String): String? {
        return try {
            val bytes = Base64.decode(encoded, Base64.NO_WRAP)
            if (bytes.size < GCM_IV_BYTES + GCM_TAG_BYTES) return null
            val iv = bytes.copyOfRange(0, GCM_IV_BYTES)
            val ct = bytes.copyOfRange(GCM_IV_BYTES, bytes.size)
            val key = getOrCreateKey()
            val cipher = Cipher.getInstance(TRANSFORMATION)
            cipher.init(Cipher.DECRYPT_MODE, key, GCMParameterSpec(GCM_TAG_BYTES * 8, iv))
            String(cipher.doFinal(ct), Charsets.UTF_8)
        } catch (t: Throwable) {
            // The most common cause is "this isn't our ciphertext"
            // (legacy plaintext value pre-migration). Log at DEBUG so
            // the migration path doesn't spam logcat. A genuine cipher
            // failure (key gone after device wipe) is rare and the
            // user-facing recovery is "re-enter the key", which the
            // null return triggers in McpSettings.
            Log.d(TAG, "decrypt failed (probably legacy plaintext): ${t.javaClass.simpleName}")
            null
        }
    }

    private fun getOrCreateKey(): SecretKey {
        val ks = KeyStore.getInstance(ANDROID_KEYSTORE).apply { load(null) }
        val existing = ks.getKey(keyAlias, null) as? SecretKey
        if (existing != null) return existing
        val generator = KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, ANDROID_KEYSTORE)
        generator.init(
            KeyGenParameterSpec.Builder(
                keyAlias,
                KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT,
            )
                .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                .setKeySize(256)
                // Authentication is NOT required — secret retrieval has
                // to work on every cold start without a biometric prompt.
                // The Keystore-bound key is still a meaningful uplift over
                // plaintext: an attacker who copies the DataStore file
                // off the device cannot decrypt without also extracting
                // the Keystore-protected AES key (TEE/StrongBox).
                .setUserAuthenticationRequired(false)
                .build(),
        )
        return generator.generateKey()
    }

    companion object {
        private const val TAG = "OrcaXR/SecretBox"
        const val DEFAULT_KEY_ALIAS: String = "orcaxr_secret_v1"
        private const val ANDROID_KEYSTORE = "AndroidKeyStore"
        private const val TRANSFORMATION = "AES/GCM/NoPadding"
        private const val GCM_IV_BYTES = 12
        private const val GCM_TAG_BYTES = 16
    }
}

/** Pass-through implementation for host-JVM unit tests. */
class PlaintextSecretBox : SecretBox {
    override fun encrypt(plaintext: String): String = plaintext
    override fun decrypt(encoded: String): String? = encoded
}
