import type { ActionDefinition as Action } from '../ActionRegistry';

export const advancedActions: Action[] = [
  {
    id: 'add_emboss',
    mcpTool: 'emboss_model',
    label: 'Emboss Text',
    icon: 'emboss',
    group: 'advanced',
    disclosure: 'menu',
    menuSection: 'tools',
    hint: 'Emboss text onto the selected model',
  },
  {
    id: 'add_magnet',
    mcpTool: 'add_magnets',
    label: 'Add Magnet Hole',
    icon: 'magnet',
    group: 'advanced',
    disclosure: 'menu',
    menuSection: 'tools',
    hint: 'Add a cavity for a magnet',
  },
  {
    id: 'auto_place_wipe',
    label: 'Auto-place Wipe Tower',
    icon: 'wipe_tower',
    group: 'advanced',
    disclosure: 'menu',
    menuSection: 'tools',
    hint: 'Automatically position the wipe tower',
    run: (ctx) => ctx.autoPlaceWipeTower(),
  },
  {
    id: 'scan_network',
    label: 'Scan Subnets',
    icon: 'network',
    group: 'advanced',
    disclosure: 'menu',
    menuSection: 'tools',
    hint: 'Scan local network for printers',
  },
  {
    id: 'view_webcam',
    label: 'View Webcam',
    icon: 'webcam',
    group: 'advanced',
    disclosure: 'menu',
    menuSection: 'tools',
    hint: 'View the live printer webcam feed',
  },
  {
    id: 'recreate_model_colors_fullspectrum',
    mcpTool: 'recreate_model_colors_fullspectrum',
    label: 'Recreate Model Colors (Full-Spectrum)',
    icon: 'palette',
    group: 'advanced',
    disclosure: 'menu',
    menuSection: 'tools',
    hint: 'Recreate model colors using printer filaments via Full-Spectrum dithering',
    isEnabled: (s) => s.modelCount > 0,
    run: (ctx) => {
      ctx.recreateModelColorsWithFullSpectrum();
    },
  },
];
