import type { Action } from '../ActionRegistry';

export const advancedActions: Action[] = [
  {
    id: 'add_emboss',
    mcpTool: 'emboss_text',
    label: 'Emboss Text',
    icon: 'title',
    group: 'advanced',
    disclosure: 'menu',
    menuSection: 'tools',
    hint: 'Emboss text onto the selected model',
    run: (ctx) => ctx.embossText(),
  },
  {
    id: 'add_magnet',
    mcpTool: 'add_magnet',
    label: 'Add Magnet Hole',
    icon: 'radio_button_unchecked',
    group: 'advanced',
    disclosure: 'menu',
    menuSection: 'tools',
    hint: 'Add a cavity for a magnet',
    run: (ctx) => ctx.addMagnet(),
  },
  {
    id: 'auto_place_wipe',
    label: 'Auto-place Wipe Tower',
    icon: 'format_align_justify',
    group: 'advanced',
    disclosure: 'menu',
    menuSection: 'tools',
    hint: 'Automatically position the wipe tower',
    run: (ctx) => ctx.autoPlaceWipeTower(),
  },
  {
    id: 'scan_network',
    label: 'Scan Subnets',
    icon: 'wifi',
    group: 'advanced',
    disclosure: 'menu',
    menuSection: 'tools',
    hint: 'Scan local network for printers',
    run: (ctx) => ctx.scanNetwork(),
  },
  {
    id: 'view_webcam',
    label: 'View Webcam',
    icon: 'videocam',
    group: 'advanced',
    disclosure: 'menu',
    menuSection: 'tools',
    hint: 'View the live printer webcam feed',
    run: (ctx) => ctx.viewWebcam(),
  },
];
