/**
 * File group — mirrors Snapmaker Orca's `File` menu (New / Open / Save project,
 * Import, Export). Import-model and Export-G-code are wired to OrcaXR's existing
 * load/download paths. Several project and export paths have local alpha
 * implementations whose remaining acceptance work is tracked in
 * `docs/parity.md`.
 *
 * Intentionally omitted OS-shell items (`New Window`, `Quit`, `Open a new
 * PrusaSlicer`) have no meaning in a single-tab web app; see the plan doc.
 */
import type { ActionDefinition as Action } from '../ActionRegistry';

export const fileActions: Action[] = [
  {
    id: 'file_new_project',
    label: 'New Project',
    icon: 'new_project',
    group: 'file',
    disclosure: 'menu',
    menuSection: 'file',
    hint: 'Clear the plate and start a fresh project',
    isEnabled: (s) => s.dirty || s.modelCount > 0 || s.plateCount > 1,
    run: (ctx) => ctx.newProject(),
  },
  {
    id: 'file_open_project',
    label: 'Open Project…',
    icon: 'folder_open',
    group: 'file',
    disclosure: 'menu',
    menuSection: 'file',
    hint: 'Open a saved .3mf project (models + plates + settings)',
    run: (ctx) => ctx.openProject(),
  },
  {
    id: 'file_import_model',
    mcpTool: 'load_model_from_path',
    label: 'Import Model…',
    icon: 'load',
    group: 'file',
    disclosure: 'menu',
    menuSection: 'file',
    hint: 'Import an STL or 3MF model',
    run: (ctx) => ctx.loadModel(),
  },
  {
    id: 'file_import_config',
    label: 'Import Config…',
    icon: 'settings_import',
    group: 'file',
    disclosure: 'menu',
    menuSection: 'file',
    hint: 'Load an Orca / Prusa printer or process config bundle',
    run: (ctx) => ctx.importConfig(),
  },
  {
    id: 'file_import_zip',
    label: 'Import Zip Archive…',
    icon: 'archive',
    group: 'file',
    disclosure: 'menu',
    menuSection: 'file',
    hint: 'Load all models contained in a .zip archive',
    run: (ctx) => ctx.importZip(),
  },
  {
    id: 'file_save_project',
    label: 'Save Project',
    icon: 'save',
    group: 'file',
    disclosure: 'menu',
    menuSection: 'file',
    hint: 'Save the current project to a .3mf file',
    isEnabled: (s) => s.modelCount > 0,
    run: (ctx) => ctx.saveProject(),
  },
  {
    id: 'file_save_project_as',
    label: 'Save Project As…',
    icon: 'save_as',
    group: 'file',
    disclosure: 'menu',
    menuSection: 'file',
    hint: 'Save the current project under a new .3mf name',
    isEnabled: (s) => s.modelCount > 0,
    run: (ctx) => ctx.saveProject(),
  },
  {
    id: 'file_export_gcode',
    mcpTool: 'save_gcode_to_downloads',
    label: 'Export G-code…',
    icon: 'download',
    group: 'file',
    disclosure: 'menu',
    menuSection: 'file',
    hint: 'Export the sliced G-code for the active plate',
    isEnabled: (s) => s.gcodeReady,
    run: (ctx) => ctx.downloadGcode(),
  },
  {
    id: 'file_export_all_plates',
    label: 'Export All Plates…',
    icon: 'download',
    group: 'file',
    disclosure: 'menu',
    menuSection: 'file',
    hint: 'Slice and export G-code for every build plate',
  },
  {
    id: 'file_export_stl',
    label: 'Export as one STL…',
    icon: 'file_stl',
    group: 'file',
    disclosure: 'menu',
    menuSection: 'file',
    hint: 'Export selected models, or every model on the active plate, from canonical geometry',
    isEnabled: (s) => s.modelCount > 0,
    run: (ctx) => ctx.exportStl(),
  },
  {
    id: 'file_export_3mf',
    label: 'Export as 3MF…',
    icon: 'file_3mf',
    group: 'file',
    disclosure: 'menu',
    menuSection: 'file',
    hint: 'Export the plated geometry as a generic 3MF',
    isEnabled: (s) => s.modelCount > 0,
    run: (ctx) => ctx.export3mf(),
  },
  {
    id: 'file_export_config',
    label: 'Export Config…',
    icon: 'settings_export',
    group: 'file',
    disclosure: 'menu',
    menuSection: 'file',
    hint: 'Export the active printer / process / filament config',
    run: (ctx) => ctx.exportConfig(),
  },
  {
    id: 'file_export_obj',
    label: 'Export Toolpaths as OBJ…',
    icon: 'file_obj',
    group: 'file',
    disclosure: 'menu',
    menuSection: 'file',
    hint: 'Export the sliced toolpaths as a Wavefront OBJ',
  },
  {
    id: 'file_open_gcode',
    label: 'Open G-code Viewer…',
    icon: 'gcode',
    group: 'file',
    disclosure: 'menu',
    menuSection: 'file',
    hint: 'Open a .gcode file in the standalone toolpath viewer',
  },
  {
    id: 'file_export_logs',
    label: 'Export Logs…',
    icon: 'logs',
    group: 'file',
    disclosure: 'menu',
    menuSection: 'file',
    hint: 'Export application logs as a ZIP for bug reports',
  },
];
