/**
 * Scene group — model import, the modal transform tools, and mesh operations.
 * Every handler routes through {@link ActionContext}; no logic lives here.
 */
import type { Action } from '../ActionRegistry';

export const sceneActions: Action[] = [
  // ---- Primary ----
  {
    id: 'load_model_from_path',
    mcpTool: 'load_model_from_path',
    label: 'Load',
    icon: 'load',
    group: 'scene',
    disclosure: 'primary',
    hint: 'Import an STL or 3MF model',
    run: (ctx) => ctx.loadModel(),
  },

  // ---- Tool rail (modal gizmos) ----
  {
    id: 'tool_move',
    mcpTool: 'set_gizmo_tool',
    label: 'Move',
    icon: 'move',
    group: 'scene',
    disclosure: 'toolbar',
    tool: 'move',
    hint: 'Move the selected model on the bed',
    run: (ctx) => ctx.setTool('move'),
  },
  {
    id: 'tool_rotate',
    mcpTool: 'set_gizmo_tool',
    label: 'Rotate',
    icon: 'rotate',
    group: 'scene',
    disclosure: 'toolbar',
    tool: 'rotate',
    hint: 'Rotate the selected model',
    run: (ctx) => ctx.setTool('rotate'),
  },
  {
    id: 'tool_scale',
    mcpTool: 'set_gizmo_tool',
    label: 'Scale',
    icon: 'scale',
    group: 'scene',
    disclosure: 'toolbar',
    tool: 'scale',
    hint: 'Scale the selected model',
    run: (ctx) => ctx.setTool('scale'),
  },
  {
    id: 'tool_lay_on_face',
    mcpTool: 'set_gizmo_tool',
    label: 'Lay flat',
    icon: 'lay_on_face',
    group: 'scene',
    disclosure: 'toolbar',
    tool: 'lay_on_face',
    hint: 'Click a face to lay it flat on the bed',
    run: (ctx) => ctx.setTool('lay_on_face'),
  },
  {
    id: 'tool_paint',
    mcpTool: 'set_paint_brush',
    label: 'Paint',
    icon: 'paint',
    group: 'paint',
    disclosure: 'toolbar',
    tool: 'paint',
    hint: 'Brush filament colours onto the model',
    run: (ctx) => ctx.setTool('paint'),
  },
  {
    id: 'drop_to_bed',
    mcpTool: 'transform_model',
    label: 'Auto-orient',
    icon: 'auto_orient',
    group: 'scene',
    disclosure: 'toolbar',
    hint: 'Rotate the model to the lowest-profile orientation',
    isEnabled: (s) => s.hasSelection,
    run: (ctx) => ctx.autoOrient(),
  },
  {
    id: 'delete_models',
    mcpTool: 'delete_models',
    label: 'Delete',
    icon: 'delete',
    group: 'scene',
    disclosure: 'toolbar',
    hint: 'Remove the selected model',
    isEnabled: (s) => s.hasSelection,
    run: (ctx) => ctx.deleteSelected(),
  },

  // ---- Add / Tools menus ----
  {
    id: 'add_handy_model',
    mcpTool: 'add_handy_model',
    label: 'Add from library',
    icon: 'library',
    group: 'scene',
    disclosure: 'menu',
    menuSection: 'add',
    hint: 'Drop in a built-in model (Benchy, cube…)',
    run: (ctx) => ctx.addFromLibrary(),
  },
  {
    id: 'add_primitive_cube',
    mcpTool: 'add_primitive',
    label: 'Cube',
    icon: 'cube',
    group: 'scene',
    disclosure: 'menu',
    menuSection: 'add',
    hint: 'Add a 20 mm cube',
    run: (ctx) => ctx.addPrimitive('cube'),
  },
  {
    id: 'add_primitive_cylinder',
    mcpTool: 'add_primitive',
    label: 'Cylinder',
    icon: 'cylinder',
    group: 'scene',
    disclosure: 'menu',
    menuSection: 'add',
    hint: 'Add a 20 mm cylinder',
    run: (ctx) => ctx.addPrimitive('cylinder'),
  },
  {
    id: 'add_primitive_sphere',
    mcpTool: 'add_primitive',
    label: 'Sphere',
    icon: 'sphere',
    group: 'scene',
    disclosure: 'menu',
    menuSection: 'add',
    hint: 'Add a 20 mm sphere',
    run: (ctx) => ctx.addPrimitive('sphere'),
  },
  {
    id: 'add_calibration_tower',
    mcpTool: 'generate_calibration_ramp',
    label: 'Calibration tower',
    icon: 'calibration',
    group: 'scene',
    disclosure: 'menu',
    menuSection: 'add',
    hint: 'Add a temperature / overhang test tower',
    run: (ctx) => ctx.addCalibration('tower'),
  },
  {
    id: 'add_calibration_cube',
    mcpTool: 'generate_calibration_ramp',
    label: 'Calibration cube',
    icon: 'calibration',
    group: 'scene',
    disclosure: 'menu',
    menuSection: 'add',
    hint: 'Add a 20 mm XYZ calibration cube',
    run: (ctx) => ctx.addCalibration('cube'),
  },
  {
    id: 'repair_model',
    mcpTool: 'repair_model',
    label: 'Repair mesh',
    icon: 'repair',
    group: 'scene',
    disclosure: 'menu',
    menuSection: 'tools',
    hint: 'Fix non-manifold geometry (ADMesh + CGAL)',
    isEnabled: (s) => s.hasSelection,
    run: (ctx) => ctx.repairSelected(),
  },
  {
    id: 'simplify_model',
    mcpTool: 'simplify_model',
    label: 'Simplify (decimate)',
    icon: 'simplify',
    group: 'scene',
    disclosure: 'menu',
    menuSection: 'tools',
    hint: 'Halve the triangle count of the selected model',
    isEnabled: (s) => s.hasSelection,
    run: (ctx) => ctx.simplifySelected(),
  },
  {
    id: 'mesh_boolean_union',
    mcpTool: 'mesh_boolean',
    label: 'Union (merge all)',
    icon: 'union',
    group: 'scene',
    disclosure: 'menu',
    menuSection: 'tools',
    hint: 'Boolean-union the selected and other model',
    isEnabled: (s) => s.modelCount >= 2,
    run: (ctx) => ctx.boolean('UNION'),
  },
  {
    id: 'add_plate',
    mcpTool: 'add_plate',
    label: 'Add build plate',
    icon: 'plate',
    group: 'system',
    disclosure: 'menu',
    menuSection: 'tools',
    hint: 'Create a new empty build plate and switch to it',
    run: (ctx) => ctx.addPlate(),
  },
  {
    id: 'delete_plate',
    mcpTool: 'delete_plate',
    label: 'Delete build plate',
    icon: 'delete',
    group: 'system',
    disclosure: 'menu',
    menuSection: 'tools',
    hint: 'Delete the active build plate',
    isEnabled: (s) => s.plateCount > 1,
    run: (ctx) => ctx.deletePlate(),
  },
  {
    id: 'mesh_boolean_subtract',
    mcpTool: 'mesh_boolean',
    label: 'Subtract (cut)',
    icon: 'subtract',
    group: 'scene',
    disclosure: 'menu',
    menuSection: 'tools',
    hint: 'Boolean-subtract the other model from the selected',
    isEnabled: (s) => s.modelCount >= 2,
    run: (ctx) => ctx.boolean('A_NOT_B'),
  },
];
