/**
 * Scene group — model import, the modal transform tools, and mesh operations.
 * Every handler routes through {@link ActionContext}; no logic lives here.
 */
import type { ActionDefinition as Action } from '../ActionRegistry';

export const sceneActions: Action[] = [
  // ---- Primary ----
  {
    id: 'load_model_from_path',
    mcpTool: 'load_model_from_path',
    label: 'Load',
    icon: 'load',
    group: 'scene',
    disclosure: 'primary',
    hint: 'Import an STL or 3MF model',
    run: (ctx) => ctx.loadModel(),
  },

  // ---- Tool rail (modal gizmos) ----
  {
    id: 'tool_move',
    mcpTool: 'set_gizmo_tool',
    label: 'Move',
    icon: 'move',
    group: 'scene',
    disclosure: 'toolbar',
    tool: 'move',
    hint: 'Move the selected model on the bed',
    shortcuts: ['G'],
    run: (ctx) => ctx.applyTool('move'),
  },
  {
    id: 'tool_rotate',
    mcpTool: 'set_gizmo_tool',
    label: 'Rotate',
    icon: 'rotate',
    group: 'scene',
    disclosure: 'toolbar',
    tool: 'rotate',
    hint: 'Rotate the selected model',
    shortcuts: ['R'],
    run: (ctx) => ctx.applyTool('rotate'),
  },
  {
    id: 'tool_scale',
    mcpTool: 'set_gizmo_tool',
    label: 'Scale',
    icon: 'scale',
    group: 'scene',
    disclosure: 'toolbar',
    tool: 'scale',
    hint: 'Scale the selected model',
    shortcuts: ['S'],
    run: (ctx) => ctx.applyTool('scale'),
  },
  {
    id: 'tool_lay_on_face',
    mcpTool: 'set_gizmo_tool',
    label: 'Lay flat',
    icon: 'lay_on_face',
    group: 'scene',
    disclosure: 'toolbar',
    tool: 'lay_on_face',
    hint: 'Click a face to lay it flat on the bed',
    run: (ctx) => ctx.applyTool('lay_on_face'),
  },
  {
    id: 'tool_paint',
    mcpTool: 'set_paint_brush',
    label: 'Paint',
    icon: 'paint',
    group: 'paint',
    disclosure: 'toolbar',
    tool: 'paint',
    hint: 'Brush filament colours onto the model',
    run: (ctx) => ctx.applyTool('paint'),
  },
  {
    id: 'add_instance',
    label: 'Add Instance',
    icon: 'duplicate',
    group: 'scene',
    disclosure: 'menu',
    menuSection: 'edit',
    hint: 'Add another instance that shares the selected object’s parts and paint',
    isEnabled: (s) => s.hasInstanceSelection,
    run: (ctx) => ctx.addInstance(),
  },
  {
    id: 'fill_bed_with_instances',
    label: 'Fill Bed with Instances',
    icon: 'arrange',
    group: 'scene',
    disclosure: 'menu',
    menuSection: 'edit',
    hint: 'Copy the selected instance into the plate’s remaining free space',
    isEnabled: (s) => s.hasInstanceSelection,
    run: (ctx) => ctx.fillBedWithInstances(),
  },
  {
    id: 'mirror_x',
    label: 'Mirror on X',
    icon: 'scale',
    group: 'scene',
    disclosure: 'menu',
    menuSection: 'edit',
    hint: 'Mirror the selection across its own X axis',
    isEnabled: (s) => s.hasInstanceSelection,
    run: (ctx) => ctx.mirrorSelected('x'),
  },
  {
    id: 'mirror_y',
    label: 'Mirror on Y',
    icon: 'scale',
    group: 'scene',
    disclosure: 'menu',
    menuSection: 'edit',
    hint: 'Mirror the selection across its own Y axis',
    isEnabled: (s) => s.hasInstanceSelection,
    run: (ctx) => ctx.mirrorSelected('y'),
  },
  {
    id: 'mirror_z',
    label: 'Mirror on Z',
    icon: 'scale',
    group: 'scene',
    disclosure: 'menu',
    menuSection: 'edit',
    hint: 'Mirror the selection across its own Z axis',
    isEnabled: (s) => s.hasInstanceSelection,
    run: (ctx) => ctx.mirrorSelected('z'),
  },
  {
    id: 'reset_rotation',
    label: 'Reset Rotation',
    icon: 'rotate',
    group: 'scene',
    disclosure: 'menu',
    menuSection: 'edit',
    hint: 'Clear the selection’s rotation without moving or rescaling it',
    isEnabled: (s) => s.hasInstanceSelection,
    run: (ctx) => ctx.resetSelectedTransform('rotation'),
  },
  {
    id: 'reset_scale',
    label: 'Reset Scale',
    icon: 'scale',
    group: 'scene',
    disclosure: 'menu',
    menuSection: 'edit',
    hint: 'Return the selection to 1× scale, clearing any mirror',
    isEnabled: (s) => s.hasInstanceSelection,
    run: (ctx) => ctx.resetSelectedTransform('scale'),
  },
  {
    id: 'center_on_plate',
    label: 'Centre on Plate',
    icon: 'arrange',
    group: 'scene',
    disclosure: 'menu',
    menuSection: 'edit',
    hint: 'Move the selection so its footprint is centred on the printable area',
    isEnabled: (s) => s.modelCount > 0,
    run: (ctx) => ctx.centerOnPlate(),
  },
  {
    id: 'drop_to_bed',
    mcpTool: 'transform_model',
    label: 'Drop to bed',
    icon: 'auto_orient',
    group: 'scene',
    disclosure: 'toolbar',
    hint: 'Move each selected model vertically until its lowest model facet touches the bed',
    isEnabled: (s) => s.hasInstanceSelection,
    run: (ctx) => ctx.dropToBed(),
  },
  {
    id: 'delete_models',
    mcpTool: 'delete_models',
    label: 'Delete',
    icon: 'delete',
    group: 'scene',
    disclosure: 'toolbar',
    hint: 'Remove the selected model',
    isEnabled: (s) => s.hasInstanceSelection,
    run: (ctx) => ctx.deleteSelected(),
  },

  // ---- Add / Tools menus ----
  {
    id: 'add_handy_model',
    mcpTool: 'add_handy_model',
    label: 'Add from library',
    icon: 'library',
    group: 'scene',
    disclosure: 'menu',
    menuSection: 'add',
    hint: 'Drop in a built-in model (Benchy, cube…)',
    run: (ctx) => ctx.addFromLibrary(),
  },
  {
    id: 'add_primitive_cube',
    mcpTool: 'add_primitive',
    label: 'Cube',
    icon: 'cube',
    group: 'scene',
    disclosure: 'menu',
    menuSection: 'add',
    hint: 'Add a 20 mm cube',
    run: (ctx) => ctx.addPrimitive('cube'),
  },
  {
    id: 'add_primitive_cylinder',
    mcpTool: 'add_primitive',
    label: 'Cylinder',
    icon: 'cylinder',
    group: 'scene',
    disclosure: 'menu',
    menuSection: 'add',
    hint: 'Add a 20 mm cylinder',
    run: (ctx) => ctx.addPrimitive('cylinder'),
  },
  {
    id: 'add_primitive_sphere',
    mcpTool: 'add_primitive',
    label: 'Sphere',
    icon: 'sphere',
    group: 'scene',
    disclosure: 'menu',
    menuSection: 'add',
    hint: 'Add a 20 mm sphere',
    run: (ctx) => ctx.addPrimitive('sphere'),
  },
  {
    id: 'add_calibration_tower',
    mcpTool: 'generate_calibration_ramp',
    label: 'Calibration tower',
    icon: 'calibration',
    group: 'scene',
    disclosure: 'menu',
    menuSection: 'add',
    hint: 'Add a temperature / overhang test tower',
    run: (ctx) => ctx.addCalibration('tower'),
  },
  {
    id: 'add_calibration_cube',
    mcpTool: 'generate_calibration_ramp',
    label: 'Calibration cube',
    icon: 'calibration',
    group: 'scene',
    disclosure: 'menu',
    menuSection: 'add',
    hint: 'Add a 20 mm XYZ calibration cube',
    run: (ctx) => ctx.addCalibration('cube'),
  },
  {
    id: 'repair_model',
    mcpTool: 'repair_model',
    label: 'Repair mesh',
    icon: 'repair',
    group: 'scene',
    disclosure: 'menu',
    menuSection: 'tools',
    hint: 'Fix non-manifold geometry (ADMesh + CGAL)',
    isEnabled: (s) => s.hasSelection,
    run: (ctx) => ctx.repairSelected(),
  },
  {
    id: 'simplify_model',
    mcpTool: 'simplify_model',
    label: 'Simplify (decimate)',
    icon: 'simplify',
    group: 'scene',
    disclosure: 'menu',
    menuSection: 'tools',
    hint: 'Halve the triangle count of the selected model',
    isEnabled: (s) => s.hasSelection,
    run: (ctx) => ctx.simplifySelected(),
  },
  {
    id: 'mesh_boolean_union',
    mcpTool: 'mesh_boolean',
    label: 'Union (merge all)',
    icon: 'union',
    group: 'scene',
    disclosure: 'menu',
    menuSection: 'tools',
    hint: 'Boolean-union the selected and other model',
    isEnabled: (s) => s.modelCount >= 2,
    run: (ctx) => ctx.boolean('UNION'),
  },
  {
    id: 'add_plate',
    mcpTool: 'add_plate',
    label: 'Add build plate',
    icon: 'plate',
    group: 'system',
    disclosure: 'menu',
    menuSection: 'tools',
    hint: 'Create a new empty build plate and switch to it',
    run: (ctx) => ctx.addPlate(),
  },
  {
    id: 'activate_plate',
    label: 'Activate build plate',
    icon: 'plate',
    group: 'system',
    disclosure: 'inspector',
    hint: 'Switch to the selected build plate',
    run: (ctx, invocation) => {
      const request = invocation.plateTarget;
      const plateId = request?.plateId ?? invocation.plateId;
      if (!plateId) {
        ctx.reportCapabilityUnavailable('Activate build plate', 'Choose a plate from the plate bar.');
        return;
      }
      ctx.activatePlate(plateId, request?.sourceRevision);
    },
  },
  {
    id: 'delete_plate',
    mcpTool: 'delete_plate',
    label: 'Delete build plate',
    icon: 'delete',
    group: 'system',
    disclosure: 'menu',
    menuSection: 'tools',
    hint: 'Delete the active build plate',
    isEnabled: (s) => s.plateCount > 1,
    run: (ctx, invocation) =>
      ctx.deletePlate(invocation.plateTarget?.plateId ?? invocation.plateId, invocation.plateTarget?.sourceRevision),
  },
  {
    id: 'rename_plate',
    label: 'Rename build plate',
    icon: 'plate',
    group: 'system',
    disclosure: 'inspector',
    hint: 'Rename the selected build plate',
    run: (ctx, invocation) => {
      const request = invocation.plateRename;
      if (!request) {
        ctx.reportCapabilityUnavailable('Rename build plate', 'Choose a plate and enter its new name.');
        return;
      }
      ctx.renamePlate(request.plateId, request.nextName, request.sourceRevision);
    },
  },
  {
    id: 'reorder_plates',
    label: 'Reorder build plates',
    icon: 'plate',
    group: 'system',
    disclosure: 'inspector',
    hint: 'Move build plates earlier or later',
    run: (ctx, invocation) => {
      const request = invocation.plateReorder;
      if (!request) {
        ctx.reportCapabilityUnavailable('Reorder build plates', 'Choose a complete plate order.');
        return;
      }
      ctx.reorderPlates(request.orderedPlateIds, request.sourceRevision);
    },
  },
  {
    id: 'set_plate_printable',
    label: 'Include build plate in printing',
    icon: 'plate',
    group: 'system',
    disclosure: 'inspector',
    hint: 'Include or exclude one build plate from print output',
    run: (ctx, invocation) => {
      const request = invocation.platePrintable;
      if (!request) {
        ctx.reportCapabilityUnavailable('Include build plate in printing', 'Choose a build plate.');
        return;
      }
      ctx.setPlatePrintable(request.plateId, request.printable, request.sourceRevision);
    },
  },
  {
    id: 'mesh_boolean_subtract',
    mcpTool: 'mesh_boolean',
    label: 'Subtract (cut)',
    icon: 'subtract',
    group: 'scene',
    disclosure: 'menu',
    menuSection: 'tools',
    hint: 'Boolean-subtract the other model from the selected',
    isEnabled: (s) => s.modelCount >= 2,
    run: (ctx) => ctx.boolean('A_NOT_B'),
  },
];
