import assert from 'node:assert/strict';
import { createServer, type IncomingMessage, type Server, type ServerResponse } from 'node:http';
import { AddressInfo } from 'node:net';

import {
  MoonrakerTransport,
  PrintJobCommandError,
  PrintJobStatusModel,
  PrintSubmissionError,
  PRINT_JOB_QUERY_PATH,
  executePrintJobCommand,
  submitPrintJob,
  summarizeGcodeToolUsage,
  validateToolMapping,
  queryMoonrakerFilamentSlots,
  type MoonrakerScheduler,
  type MoonrakerSocket,
} from '..';

/**
 * End-to-end print submission against a Moonraker simulator.
 *
 * Unlike the unit suite, this drives the real `MoonrakerTransport` over real
 * HTTP: the multipart body, the bare (unwrapped) upload response, credential
 * headers, and the stored bytes are all exercised as the printer would see
 * them.
 */

const SERVER_INFO = Object.freeze({
  api_version: [1, 0, 5],
  moonraker_version: 'v0.9.3-1',
  components: ['authorization', 'file_manager', 'history', 'job_queue', 'klippy_apis', 'webcam', 'u1_ext'],
  warnings: [],
});
const PRINTER_INFO = Object.freeze({ state: 'ready', hostname: 'u1-simulator', software_version: 'v0.12.0' });

const MULTICOLOR_GCODE = [
  '; generated by OrcaXR',
  'T0',
  'G1 X10 Y10 E1',
  'T1',
  'G1 X20 Y20 E1',
  '; filament_colour = #FF0000;#00FF00',
  '; filament_type = PLA;PLA-CF',
  '',
].join('\n');

interface SimulatorOptions {
  klippy?: string;
  printState?: string;
  files?: string[];
  /** Report a size that differs from the stored bytes (corrupted transfer). */
  reportedSizeDelta?: number;
}

/** Mirrors Moonraker's documented POST-only endpoints. */
const REQUIRED_METHODS: Readonly<Record<string, string | undefined>> = Object.freeze({
  '/printer/print/start': 'POST',
  '/printer/print/pause': 'POST',
  '/printer/print/resume': 'POST',
  '/printer/print/cancel': 'POST',
  '/printer/emergency_stop': 'POST',
  '/printer/firmware_restart': 'POST',
  '/printer/gcode/script': 'POST',
  '/server/files/move': 'POST',
});

class Simulator {
  readonly stored = new Map<string, Buffer>();
  readonly requests: string[] = [];
  readonly methods: string[] = [];
  readonly apiKeys: (string | undefined)[] = [];
  readonly lifecycle: string[] = [];
  started: string | null = null;
  klippy: string;
  printState: string;
  private readonly server: Server;
  private port = 0;

  constructor(private readonly options: SimulatorOptions = {}) {
    for (const name of options.files ?? []) this.stored.set(name, Buffer.alloc(1));
    this.klippy = options.klippy ?? 'ready';
    this.printState = options.printState ?? 'standby';
    this.server = createServer((request, response) => void this.handle(request, response));
  }

  async listen(): Promise<string> {
    await new Promise<void>((resolve) => this.server.listen(0, '127.0.0.1', resolve));
    this.port = (this.server.address() as AddressInfo).port;
    return `http://127.0.0.1:${this.port}`;
  }

  async close(): Promise<void> {
    await new Promise<void>((resolve, reject) => this.server.close((error) => (error ? reject(error) : resolve())));
  }

  private async handle(request: IncomingMessage, response: ServerResponse): Promise<void> {
    const url = new URL(request.url ?? '/', `http://127.0.0.1:${this.port}`);
    this.requests.push(url.pathname);
    this.methods.push(`${request.method} ${url.pathname}`);
    this.apiKeys.push(request.headers['x-api-key'] as string | undefined);
    const json = (payload: unknown, bare = false) => {
      response.writeHead(200, { 'content-type': 'application/json' });
      response.end(JSON.stringify(bare ? payload : { result: payload }));
    };

    // Real Moonraker serves these for POST only and answers 405 otherwise.
    // Recording just the pathname let the client send every print command as a
    // GET while these tests stayed green.
    const requiredMethod = REQUIRED_METHODS[url.pathname];
    if (requiredMethod !== undefined && request.method !== requiredMethod) {
      response.writeHead(405, { 'content-type': 'application/json', allow: requiredMethod });
      response.end(JSON.stringify({ error: { code: 405, message: `Method ${request.method} not allowed` } }));
      return;
    }

    if (url.pathname === '/server/info') return json(SERVER_INFO);
    if (url.pathname === '/printer/info') return json(PRINTER_INFO);
    if (url.pathname === '/printer/objects/query') {
      if (url.searchParams.has('print_task_config')) {
        return json({
          status: {
            print_task_config: {
              filament_color_rgba: ['#FF0000FF', '#00FF00FF'],
              filament_type: ['PLA', 'PLA-CF'],
              filament_vendor: ['Elegoo', 'Elegoo'],
              filament_exist: [1, 1],
            },
          },
        });
      }
      return json({
        status: {
          webhooks: { state: this.klippy },
          print_stats: {
            state: this.printState,
            filename: this.started ?? '',
            print_duration: this.printState === 'standby' ? 0 : 240,
            info: this.printState === 'standby' ? {} : { current_layer: 11, total_layer: 98 },
          },
          virtual_sdcard: {
            is_active: this.printState === 'printing',
            progress: this.printState === 'standby' ? 0 : 0.2,
          },
          extruder: { temperature: 219.6, target: this.printState === 'printing' ? 220 : 0 },
          heater_bed: { temperature: 59.7, target: this.printState === 'printing' ? 60 : 0 },
        },
      });
    }
    if (url.pathname === '/server/files/list') {
      return json([...this.stored.keys()].map((path) => ({ path, modified: 0, size: this.stored.get(path)?.length })));
    }
    if (url.pathname === '/server/files/upload') {
      const body = await readBody(request);
      const parsed = parseSingleFileMultipart(body, request.headers['content-type'] ?? '');
      this.stored.set(parsed.filename, parsed.content);
      // Moonraker answers uploads with an unwrapped object, unlike every other
      // endpoint; the transport must accept it without loosening the rest.
      return json({ item: { path: parsed.filename, root: 'gcodes' }, print_started: false }, true);
    }
    if (url.pathname === '/server/files/metadata') {
      const filename = url.searchParams.get('filename') ?? '';
      const content = this.stored.get(filename);
      if (!content) {
        response.writeHead(404, { 'content-type': 'application/json' });
        response.end(JSON.stringify({ error: { message: 'not found' } }));
        return;
      }
      return json({ filename, size: content.length + (this.options.reportedSizeDelta ?? 0) });
    }
    if (url.pathname === '/printer/print/start') {
      this.started = url.searchParams.get('filename');
      this.printState = 'printing';
      return json('ok');
    }
    if (url.pathname === '/printer/print/pause') {
      this.lifecycle.push('pause');
      this.printState = 'paused';
      return json('ok');
    }
    if (url.pathname === '/printer/print/resume') {
      this.lifecycle.push('resume');
      this.printState = 'printing';
      return json('ok');
    }
    if (url.pathname === '/printer/print/cancel') {
      this.lifecycle.push('cancel');
      this.printState = 'cancelled';
      return json('ok');
    }
    if (url.pathname === '/printer/emergency_stop') {
      this.lifecycle.push('emergency-stop');
      this.klippy = 'shutdown';
      return json('ok');
    }
    response.writeHead(404, { 'content-type': 'application/json' });
    response.end(JSON.stringify({ error: { message: 'unknown path' } }));
  }
}

class ImmediateSocket implements MoonrakerSocket {
  readyState = 0;
  onopen: ((event: unknown) => void) | null = null;
  onmessage: ((event: { readonly data: unknown }) => void) | null = null;
  onerror: ((event: unknown) => void) | null = null;
  onclose: ((event: { readonly code?: number; readonly reason?: string }) => void) | null = null;

  constructor(readonly url: string) {
    queueMicrotask(() => {
      this.readyState = 1;
      this.onopen?.({});
    });
  }

  send(): void {}
  close(): void {
    this.readyState = 3;
  }
}

const realScheduler: MoonrakerScheduler = {
  setTimeout: (callback, delayMs) => setTimeout(callback, delayMs),
  clearTimeout: (handle) => clearTimeout(handle as ReturnType<typeof setTimeout>),
};

async function withPrinter<T>(
  options: SimulatorOptions,
  run: (context: { transport: MoonrakerTransport; simulator: Simulator }) => Promise<T>,
): Promise<T> {
  const simulator = new Simulator(options);
  const endpoint = await simulator.listen();
  const transport = new MoonrakerTransport(
    { endpoint, clientName: 'OrcaXR Web', clientVersion: 'test' },
    { socketFactory: (url) => new ImmediateSocket(url), scheduler: realScheduler, heartbeatIntervalMs: 60_000 },
  );
  transport.setSessionCredentials({ apiKey: 'simulator-key' });
  try {
    await transport.connect();
    return await run({ transport, simulator });
  } finally {
    transport.dispose();
    await simulator.close();
  }
}

let passed = 0;
async function test(name: string, run: () => Promise<void>): Promise<void> {
  await run();
  passed += 1;
  console.log(`  ✓ ${name}`);
}

await test('uploads a multicolor artifact byte-for-byte and starts it once confirmed', async () => {
  await withPrinter({}, async ({ transport, simulator }) => {
    const slots = await queryMoonrakerFilamentSlots(transport);
    const mapping = validateToolMapping(summarizeGcodeToolUsage(MULTICOLOR_GCODE), slots);
    assert.deepEqual(mapping.blockers, [], 'both tools are loaded on the simulated printer');
    assert.deepEqual(mapping.warnings, []);

    const phases: string[] = [];
    const result = await submitPrintJob(transport, {
      filename: 'PeggyPalette Plate 1.gcode',
      gcode: MULTICOLOR_GCODE,
      startPrint: true,
      onPhase: (phase) => phases.push(phase),
    });

    assert.equal(result.path, 'PeggyPalette_Plate_1.gcode');
    assert.equal(result.startedPrint, true);
    assert.equal(simulator.started, 'PeggyPalette_Plate_1.gcode');
    assert.equal(
      simulator.stored.get('PeggyPalette_Plate_1.gcode')?.toString('utf8'),
      MULTICOLOR_GCODE,
      'the printer stored exactly the submitted artifact',
    );
    assert.equal(result.verifiedBytes, Buffer.byteLength(MULTICOLOR_GCODE));
    assert.deepEqual(phases, ['checking', 'uploading', 'verifying', 'starting', 'done']);
    assert.ok(
      simulator.apiKeys.every((key) => key === 'simulator-key'),
      'every simulated request carried the session credential',
    );
    assert.ok(
      simulator.methods.includes('POST /printer/print/start'),
      'starting a print is a POST; Moonraker answers a GET with 405',
    );
  });
});

await test('reports a tool the printer cannot supply before anything is sent', async () => {
  await withPrinter({}, async ({ transport }) => {
    const threeToolGcode = `${MULTICOLOR_GCODE}T2\nG1 X30 Y30 E1\n`;
    const mapping = validateToolMapping(
      summarizeGcodeToolUsage(threeToolGcode),
      await queryMoonrakerFilamentSlots(transport),
    );
    assert.deepEqual(
      mapping.blockers.map((notice) => notice.toolIndex),
      [2],
    );
  });
});

await test('picks an unused name instead of replacing a stored file', async () => {
  await withPrinter({ files: ['plate.gcode'] }, async ({ transport, simulator }) => {
    const renamed = await submitPrintJob(transport, { filename: 'plate.gcode', gcode: MULTICOLOR_GCODE });
    assert.equal(renamed.path, 'plate_2.gcode');
    assert.equal(simulator.stored.get('plate.gcode')?.length, 1, 'the existing file was left untouched');

    const replaced = await submitPrintJob(transport, {
      filename: 'plate.gcode',
      gcode: MULTICOLOR_GCODE,
      overwrite: true,
    });
    assert.equal(replaced.path, 'plate.gcode');
    assert.equal(simulator.stored.get('plate.gcode')?.toString('utf8'), MULTICOLOR_GCODE);
  });
});

await test('refuses to start a print on a busy printer', async () => {
  await withPrinter({ printState: 'printing' }, async ({ transport, simulator }) => {
    await assert.rejects(
      () => submitPrintJob(transport, { filename: 'plate.gcode', gcode: MULTICOLOR_GCODE, startPrint: true }),
      (error: unknown) => error instanceof PrintSubmissionError && error.code === 'not-ready',
    );
    assert.equal(simulator.started, null);
    assert.equal(simulator.stored.size, 0, 'a refused start uploads nothing');
  });
});

await test('never starts a print when the stored size disagrees with the transfer', async () => {
  await withPrinter({ reportedSizeDelta: -12 }, async ({ transport, simulator }) => {
    await assert.rejects(
      () => submitPrintJob(transport, { filename: 'plate.gcode', gcode: MULTICOLOR_GCODE, startPrint: true }),
      (error: unknown) => error instanceof PrintSubmissionError && error.code === 'verification-failed',
    );
    assert.equal(simulator.started, null);
  });
});

await test('reads the live job and drives its lifecycle through the real transport', async () => {
  await withPrinter({}, async ({ transport, simulator }) => {
    const status = new PrintJobStatusModel();
    const read = async () => status.applyQuery(await transport.request<unknown>(PRINT_JOB_QUERY_PATH));

    assert.equal((await read()).state, 'standby');
    await submitPrintJob(transport, { filename: 'plate.gcode', gcode: MULTICOLOR_GCODE, startPrint: true });

    const printing = await read();
    assert.equal(printing.state, 'printing');
    assert.equal(printing.filename, 'plate.gcode');
    assert.equal(printing.currentLayer, 11);
    assert.equal(printing.totalLayers, 98);
    assert.deepEqual(printing.extruder, { actualC: 219.6, targetC: 220 });

    // Cancelling the wrong job must be impossible even when the state allows it.
    await assert.rejects(
      () =>
        executePrintJobCommand(transport, {
          command: 'cancel',
          observed: printing,
          expectedFilename: 'a_different_plate.gcode',
        }),
      (error: unknown) => error instanceof PrintJobCommandError && error.code === 'job-changed',
    );
    assert.deepEqual(simulator.lifecycle, []);

    await executePrintJobCommand(transport, { command: 'pause', observed: printing });
    const paused = await read();
    assert.equal(paused.state, 'paused');
    await executePrintJobCommand(transport, { command: 'resume', observed: paused });
    const resumed = await read();
    assert.equal(resumed.state, 'printing');
    await executePrintJobCommand(transport, {
      command: 'cancel',
      observed: resumed,
      expectedFilename: 'plate.gcode',
    });
    assert.equal((await read()).state, 'cancelled');
    assert.deepEqual(simulator.lifecycle, ['pause', 'resume', 'cancel']);
    // Every job command mutates the machine, so every one of them is a POST.
    for (const command of ['pause', 'resume', 'cancel']) {
      assert.ok(simulator.methods.includes(`POST /printer/print/${command}`), `${command} must be sent as a POST`);
    }
  });
});

await test('halts a machine whose Klipper is down, where nothing else is allowed', async () => {
  await withPrinter({ klippy: 'shutdown' }, async ({ transport, simulator }) => {
    const status = new PrintJobStatusModel();
    const observed = status.applyQuery(await transport.request<unknown>(PRINT_JOB_QUERY_PATH));
    await assert.rejects(
      () => executePrintJobCommand(transport, { command: 'pause', observed }),
      (error: unknown) => error instanceof PrintJobCommandError && error.code === 'not-allowed',
    );
    await executePrintJobCommand(transport, { command: 'emergency-stop', observed });
    assert.deepEqual(simulator.lifecycle, ['emergency-stop']);
  });
});

console.log(`\nMoonraker print simulator: ${passed} tests passed.`);

async function readBody(request: IncomingMessage): Promise<Buffer> {
  const chunks: Buffer[] = [];
  for await (const chunk of request) chunks.push(chunk as Buffer);
  return Buffer.concat(chunks);
}

/** Minimal multipart reader: enough to prove the exact bytes crossed the wire. */
function parseSingleFileMultipart(body: Buffer, contentType: string): { filename: string; content: Buffer } {
  const boundary = /boundary=(?:"([^"]+)"|([^;]+))/i.exec(contentType);
  assert.ok(boundary, `expected a multipart boundary in ${contentType}`);
  const delimiter = `--${boundary[1] ?? boundary[2]}`;
  const parts = body.toString('binary').split(delimiter);
  for (const part of parts) {
    const headerEnd = part.indexOf('\r\n\r\n');
    if (headerEnd < 0) continue;
    const headers = part.slice(0, headerEnd);
    const filename = /filename="([^"]*)"/i.exec(headers)?.[1];
    if (!filename) continue;
    const content = part.slice(headerEnd + 4, part.lastIndexOf('\r\n'));
    return { filename, content: Buffer.from(content, 'binary') };
  }
  throw new Error('the upload carried no file part');
}
