import assert from 'node:assert/strict';

import type { MoonrakerFilamentSlot } from '../MoonrakerFilamentSlots';
import { summarizeGcodeToolUsage, validateToolMapping } from '../PrintToolMapping';

let passed = 0;
function test(name: string, run: () => void): void {
  run();
  passed += 1;
  console.log(`  ✓ ${name}`);
}

const MULTICOLOR = [
  '; generated by OrcaXR',
  'T0',
  'G1 X10 Y10 E1',
  'M620 S1A',
  'T1',
  'G1 X20 Y20 E1',
  'T255',
  '; filament_colour = #FF0000;#00FF00',
  '; filament_type = PLA;PLA-CF',
  '',
].join('\n');

function slot(index: number, material: string, colorHex: string): MoonrakerFilamentSlot {
  return { slotIndex: index, material, colorHex, vendor: 'Elegoo' };
}

test('reads the tools a multicolor artifact actually uses', () => {
  const usage = summarizeGcodeToolUsage(MULTICOLOR);
  assert.deepEqual(usage.tools, [0, 1], 'T255 is a slicer sentinel, not a slot');
  assert.equal(usage.multiMaterial, true);
  assert.deepEqual(usage.declaredColors, ['#FF0000', '#00FF00']);
  assert.deepEqual(usage.declaredMaterials, ['PLA', 'PLA-CF']);
});

test('treats a single-tool artifact as single material', () => {
  const usage = summarizeGcodeToolUsage('T0\nG1 X1 E1\n');
  assert.deepEqual(usage.tools, [0]);
  assert.equal(usage.multiMaterial, false);
  assert.deepEqual(usage.declaredColors, []);
});

test('accepts a printer whose loaded slots match the artifact', () => {
  const report = validateToolMapping(summarizeGcodeToolUsage(MULTICOLOR), [
    slot(0, 'PLA', '#FF0000'),
    // The printer reports material families, so a PLA-CF artifact matches a
    // slot reported as PLA rather than raising a false mismatch.
    slot(1, 'PLA', '#00FF00'),
  ]);
  assert.deepEqual(report.blockers, []);
  assert.deepEqual(report.warnings, []);
});

test('blocks a tool with no loaded filament', () => {
  const report = validateToolMapping(summarizeGcodeToolUsage(MULTICOLOR), [slot(0, 'PLA', '#FF0000')]);
  assert.deepEqual(
    report.blockers.map((notice) => [notice.code, notice.toolIndex]),
    [['missing-slot', 1]],
  );
  assert.match(report.blockers[0].message, /slot 2/);
});

test('warns about material and colour differences without blocking', () => {
  const report = validateToolMapping(summarizeGcodeToolUsage(MULTICOLOR), [
    slot(0, 'PETG', '#FF0000'),
    slot(1, 'PLA', '#0000FF'),
  ]);
  assert.deepEqual(report.blockers, []);
  assert.deepEqual(
    report.warnings.map((notice) => notice.code),
    ['material-mismatch', 'color-mismatch'],
  );
});

test('warns when a multicolor job cannot be checked against the printer', () => {
  const unknown = validateToolMapping(summarizeGcodeToolUsage(MULTICOLOR), []);
  assert.deepEqual(unknown.blockers, []);
  assert.deepEqual(
    unknown.warnings.map((notice) => notice.code),
    ['slots-unknown'],
  );
  const singleColor = validateToolMapping(summarizeGcodeToolUsage('T0\nG1 X1 E1\n'), undefined);
  assert.deepEqual(singleColor.warnings, [], 'a single-tool job needs no slot report');
});

console.log(`\nPrint tool mapping: ${passed} tests passed.`);
